apiVersion: ecosystem.demo.orkestra.io/v1alpha1
kind: PlatformResource
metadata:
  name: my-webapp
  namespace: default
  labels:
    team: platform
spec:
  workloadType: app
  team: platform
  repo: "github.com/myorg/services"
  path: "apps/webapp"
  branch: "main"
  targetNamespace: "production"
