apiVersion: ecosystem.demo.orkestra.io/v1alpha1
kind: PlatformResource
metadata:
  name: api-cert
  namespace: default
  labels:
    team: platform
spec:
  workloadType: cert
  team: platform
  domain: "api.myorg.io"
  issuer: "letsencrypt-prod"
