apiVersion: platform.demo.orkestra.io/v1alpha1
kind: InfraClaim
metadata:
  name: db-claim
  namespace: default
  labels:
    team: database
spec:
  workloadType: infra
  team: database
  provider: aws
  region: eu-west-1
  class: db
  