// pkg/typeregistry/zz_generated_typeregistry.go
// Code generated by "ork generate registry" on 2026-08-16T20:29:01Z. DO NOT EDIT.
// Re-generate by running: ork generate registry --file <path-or-url>
//
// This file registers compiled Go types and external functions.
// Dynamic template CRDs do not appear here — they are handled at runtime
// by GenericReconciler without any code generation.
package typeregistry

import (
	"github.com/orkspace/orkestra/domain"
	"github.com/orkspace/orkestra/pkg/logger"
	orktypes "github.com/orkspace/orkestra/pkg/types"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	bcappwithtargetsv1 "github.com/orkspace/orkestra-args-hooks-targets/api/v1alpha1"
	bchooks "github.com/orkspace/orkestra-args-hooks-targets/hooks"
)

// init runs before main(). It calls RegisterRuntimeObjects to populate the
// GVK-keyed registries and appends AddToScheme functions to SchemeAdderFns so
// that NewSchemeRegistry can find them through the internal pkg/typeregistry stub.
//
// A blank import of this package from main.go is the only wiring needed:
//
//	import _ "myapp/pkg/typeregistry"
//
// "ork generate registry -k <katalog.yaml>" populates this
//
// No explicit call to RegisterRuntimeObjects or RegisterTypedScheme is required.
func init() {
	logger.Debug().Msg("typeregistry.init() started")
	RegisterRuntimeObjects()
	orktypes.SchemeAdderFns = append(orktypes.SchemeAdderFns, func(s *runtime.Scheme) error {
		s.AddKnownTypeWithName(schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "BlockchainAppWithTargets"}, &bcappwithtargetsv1.BlockchainAppWithTargets{})
		s.AddKnownTypeWithName(schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "BlockchainAppWithTargetsList"}, &bcappwithtargetsv1.BlockchainAppWithTargetsList{})
		metav1.AddToGroupVersion(s, schema.GroupVersion{Group: "demo.orkestra.io", Version: "v1alpha1"})
		return nil
	})
	logger.Debug().Int("length", len(orktypes.SchemeAdderFns)).Msg("typeregistry.init() finished")
}

// RegisterRuntimeObjects populates ObjectRegistry, ListRegistry, HookRegistry,
// and ReconcilerRegistry. Called by init() — do not call directly.
//
// Object/List entries — factory functions for typed CRDs.
//
//	Used by the informer to create zero-value instances for cache storage
//	and type assertion during reconciliation.
//
// Hook entries — factory functions for Go hook implementations.
//
//	Called by addHooks() during Katalog validation to wire HookFactory
//	onto the CRD entry. GenericReconciler calls HookFactory() once at
//	startCRDWorkers time to obtain the typed hooks.
//
// Reconciler entries — constructor functions for custom reconcilers.
//
//	Called by addReconcilers() during Katalog validation to wire Constructor
//	onto the CRD entry. DependencyKordinator calls Constructor() once at
//	startCRDWorkers time to build the reconciler.
func RegisterRuntimeObjects() {
	logger.Debug().Msg("RegisterRuntimeObjects called")

	// BlockchainAppWithTargets — typed CRD object and list factories
	orktypes.ObjectRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "BlockchainAppWithTargets"}] =
		func() runtime.Object { return &bcappwithtargetsv1.BlockchainAppWithTargets{} }
	orktypes.ListRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "BlockchainAppWithTargets"}] =
		func() runtime.Object { return &bcappwithtargetsv1.BlockchainAppWithTargetsList{} }

	// BlockchainAppWithTargets — Go hook factory
	// Calls bchooks.BlockchainAppHooks() to obtain typed ReconcileHooks.
	orktypes.HookRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "BlockchainAppWithTargets"}] =
		func() domain.AnyReconcileHooks {
			return bchooks.BlockchainAppHooks()
		}

	logger.Debug().
		Int("objectRegistrySize", len(orktypes.ObjectRegistry)).
		Int("listRegistrySize", len(orktypes.ListRegistry)).
		Int("hookRegistrySize", len(orktypes.HookRegistry)).
		Msg("Runtime objects registered")
}
