name        = "Orkestra"
license     = "MIT"
licenselink = "https://github.com/orkspace/orkestra/blob/main/LICENSE"
description = "Custom Hugo theme for orkestra.sh — inspired by Crossplane and Kubernetes"
min_version = "0.120.0"
