apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.demo.orkestra.io
spec:
  group: demo.orkestra.io
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    shortNames: [pl]

  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Step
          type: string
          jsonPath: .status.currentStep
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [image, steps]
              properties:
                image:
                  type: string
                  description: Runner image for all steps
                steps:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required: [name, command]
                    properties:
                      name:
                        type: string
                        description: Step name
                      command:
                        type: string
                        description: Shell command to execute
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
