apiVersion: rkguide.demo/v1
kind: Cache
metadata:
  name: my-cache
  namespace: default
spec:
  image: "redis:7"
  port: 6379
  storageSize: 5Gi
  storageClass: standard
  resourceProfile: burst
  replicas: 1