# Namespaces are created manually for now
# Not implemented yet
apiVersion: v1
kind: Namespace
metadata:
  name: payments-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: payments-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: payments-dev
