apiVersion: orkestra.orkspace.io/v1
kind: Simulate
metadata:
  name: endpoint-control-simulate
  description: >
    Runs simulate for all three endpoint-control examples in sequence.

imports:
  - 01-selective-health/simulate.yaml
  - 02-full-disable/simulate.yaml
  - 03-fully-dark/simulate.yaml
