apiVersion: provisioner.orkestra.io/v1
kind: NamespaceClaim
metadata:
  name: team-gamma-claim
spec:
  targetNamespace: team-gamma
  team: gamma
  owner: gamma-operator
  ownerNamespace: default
  tier: medium
