apiVersion: orkestra.orkspace.io/v1
kind: Simulate
metadata:
  name: komposer-basic-sim
  description: Verify the Deployment and Service are created in cycle 1 via the composed operator

spec:
  katalog: ./komposer.yaml
  cr: ./cr.yaml
  cycles: 5

  expect:
    steady: true
    noErrors: true
    ops:
      - cycle: 1
        verb: create
        resource: deployments
        name: composed-site-deployment
      - cycle: 1
        verb: create
        resource: services
        name: composed-site-svc
