name: Publish webapp-operator

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Publish to registry
        uses: orkspace/orkestra-action@v1
        with:
          template: "true"
          validate: "true"
          simulate: "true"
          registry-push: "webapp-operator:${{ github.ref_name }} ."
          registry-url: "ghcr.io/${{ env.OWNER }}/katalogs"
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./webapp-operator
