# ───────────────────────────────────────────────────────────────
# ServiceAccount
# ───────────────────────────────────────────────────────────────
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orkestra
  namespace: orkestra
---
# ───────────────────────────────────────────────────────────────
# RBAC — Orkestra needs cluster-wide access to CRDs + workloads
# ───────────────────────────────────────────────────────────────
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orkestra
rules:
  # Allow watching your CRDs
  - apiGroups: ["demo.orkestra.io"]
    resources: ["websites"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Allow managing child resources (Deployments, Services, etc.)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Allow reading namespaces (common for controllers)
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  
  # Allow getting leases
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]

  # Allow creating events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  # Allow Admission webhooks
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs: ["get", "create", "update", "patch", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orkestra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orkestra
subjects:
  - kind: ServiceAccount
    name: orkestra
    namespace: orkestra
