apiVersion: provisioner.orkestra.io/v1
kind: NamespaceClaim
metadata:
  name: team-alpha-claim
spec:
  targetNamespace: team-alpha
  team: alpha
  owner: alpha-operator
  ownerNamespace: default
  limits:
    maxPods: 20
    cpu: "4"
    memory: "8Gi"
