// initialize/registry.go
// Code generated by "ork generate registry" on 2026-03-14T00:33:27Z. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
package initialize

import (
	"fmt"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	projv1 "github.com/ialexeze/orkestra/api/types/project/v1alpha1"

	mnsv1 "github.com/ialexeze/orkestra/api/types/managedNamespace/v1alpha1"

	appv1 "github.com/ialexeze/orkestra/api/types/application/v1alpha1"
)

// RegisterRuntimeObjects populates ObjectRegistry and ListRegistry for all
// enabled CRDs with reconciler.default: true in the Katalog.
// Called by NewKatalog() in YAML mode before Katalog validation.
func RegisterRuntimeObjects() {

	// Project
	ObjectRegistry[schema.GroupVersionKind{
		Group:   "platform.orkestra.io",
		Version: "v1alpha1",
		Kind:    "Project",
	}] = func() runtime.Object { return &projv1.Project{} }

	ListRegistry[schema.GroupVersionKind{
		Group:   "platform.orkestra.io",
		Version: "v1alpha1",
		Kind:    "Project",
	}] = func() runtime.Object { return &projv1.ProjectList{} }

	// ManagedNamespace
	ObjectRegistry[schema.GroupVersionKind{
		Group:   "platform.orkestra.io",
		Version: "v1alpha1",
		Kind:    "ManagedNamespace",
	}] = func() runtime.Object { return &mnsv1.ManagedNamespace{} }

	ListRegistry[schema.GroupVersionKind{
		Group:   "platform.orkestra.io",
		Version: "v1alpha1",
		Kind:    "ManagedNamespace",
	}] = func() runtime.Object { return &mnsv1.ManagedNamespaceList{} }

	// Application
	ObjectRegistry[schema.GroupVersionKind{
		Group:   "platform.orkestra.io",
		Version: "v1alpha1",
		Kind:    "Application",
	}] = func() runtime.Object { return &appv1.Application{} }

	ListRegistry[schema.GroupVersionKind{
		Group:   "platform.orkestra.io",
		Version: "v1alpha1",
		Kind:    "Application",
	}] = func() runtime.Object { return &appv1.ApplicationList{} }
}

// RegisterScheme registers all generated CRD types into the provided scheme.
// Called by NewSchemeRegistry() in YAML mode.
func RegisterScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
	if err := projv1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register Project scheme: %w", err)
	}
	if err := mnsv1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register ManagedNamespace scheme: %w", err)
	}
	if err := appv1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register Application scheme: %w", err)
	}
	return scheme, nil
}
