// initialize/types.go
package initialize

import (
	"time"

	"github.com/ialexeze/orkestra/domain"
	"github.com/ialexeze/orkestra/pkg/reconciler"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// ── Registries ────────────────────────────────────────────────────────────────
// Populated by RegisterRuntimeObjects() — generated by `ork generate` for
// default reconciler CRDs, hand-written for custom reconciler CRDs.
// Keyed by schema.GroupVersionKind — set during Katalog validation via setGroupVersionKind().

var ObjectRegistry = map[schema.GroupVersionKind]func() runtime.Object{}
var ListRegistry = map[schema.GroupVersionKind]func() runtime.Object{}

// ── APITypes ──────────────────────────────────────────────────────────────────
// Mirrors the apiTypes block in crd-katalog.yaml.
// All fields here are sourced from YAML — nothing is inferred.
// ork generate reads this block to emit initialize/registry.go.

type APITypes struct {
	// Go type names — used by ork generate to emit ObjectRegistry entries.
	Object string `yaml:"object" validate:"required"` // e.g. "Project"
	List   string `yaml:"list" validate:"required"`   // e.g. "ProjectList"

	// Import alias — optional. Defaults to last segment of Location if not set.
	// e.g. "projv1" → import projv1 "github.com/.../project/v1alpha1"
	Alias string `yaml:"alias" validate:"omitempty"`

	// GVK fields — used to construct schema.GroupVersionKind for registry keying.
	Group   string `yaml:"group" validate:"required,hostname_rfc1123"`
	Version string `yaml:"version" validate:"required"`
	Kind    string `yaml:"kind" validate:"required"`
	Plural  string `yaml:"plural" validate:"required"`

	// APIPath — defaults to /apis. Override only for core Kubernetes types (/api).
	APIPath string `yaml:"apiPath" validate:"omitempty"`

	// Location — fully qualified Go package import path.
	// e.g. "github.com/ialexeze/orkestra/api/types/project/v1alpha1"
	// Used by ork generate to emit import statements and scheme registration.
	Location string `yaml:"location" validate:"required"`
}

// ── Queue ─────────────────────────────────────────────────────────────────────

type Queue struct {
	// Default: true — CRD uses the shared default workqueue instead of a per-CRD queue.
	// Suitable for low-volume CRDs or when queue isolation is not required.
	Default bool `yaml:"default"`

	// MaxQueueDepth — per-CRD queue depth limit.
	// 0 means use the Orkestra-level default (MAX_QUEUE_DEPTH env var).
	MaxQueueDepth int `yaml:"maxQueueDepth" validate:"omitempty,gte=0"`

	// DegradeThreshold — number of consecutive reconcile failures before
	// the CRD is marked degraded. 0 means use the Orkestra-level default.
	DegradeThreshold int `yaml:"degradeThreshold" validate:"omitempty,gte=0"`
}

// ── ReconcilerConfig ──────────────────────────────────────────────────────────

type ReconcilerConfig struct {
	// Default: true  → GenericReconciler is used. HookFactory is optional.
	// Default: false → Constructor must be provided.
	Default bool `yaml:"default" validate:"omitempty"`

	// Finalizers — per-CRD finalizers. Overrides the Katalog-level finalizer.
	// Applied by GenericReconciler on create, stripped before delete.
	Finalizers []string `yaml:"finalizers" validate:"omitempty"`

	// HookFactory — called once at startCRDWorkers time to get typed hooks.
	// Only used when Default: true.
	// nil → pure GenericReconciler: finalizers, events, metrics — zero user code.
	HookFactory func() domain.AnyReconcileHooks `yaml:"-"`

	// Constructor — called once at startCRDWorkers time to build a custom reconciler.
	// Only used when Default: false. Must not be nil when Default: false —
	// enforced by Katalog validation.
	Constructor reconciler.NewReconcilerFunc `yaml:"-"`
}

// ── CRDEntry ──────────────────────────────────────────────────────────────────
// One entry per CRD in the Katalog.
// YAML fields are populated by the YAML parser or by BuildKatalogFromGo().
// Fields tagged yaml:"-" are Go-only — populated at runtime, never from YAML.

type CRDEntry struct {
	// ── Identity ──────────────────────────────────────────────────────────────
	Name        string `yaml:"name" validate:"required,hostname_rfc1123"`
	Enabled     bool   `yaml:"enabled"`
	Critical    bool   `yaml:"critical"` // controller degrades if this CRD degrades
	Description string `yaml:"description" validate:"omitempty"`

	// ── API Types ─────────────────────────────────────────────────────────────
	// Mirrors the apiTypes block in YAML.
	// In Go mode these are set directly on the entry — APITypes is populated
	// by setGroupVersionKind() from the individual fields for consistency.
	APITypes APITypes `yaml:"apiTypes" validate:"required"`

	// ── Runtime objects ───────────────────────────────────────────────────────
	// Go mode  — set directly in BuildKatalogFromGo().
	// YAML mode — populated by addRuntimeObjects() from ObjectRegistry/ListRegistry.
	// Never set from YAML directly.
	ObjectGoMode       runtime.Object        `yaml:"-"`
	ListObjectGoMode   runtime.Object        `yaml:"-"`
	ObjectYamlMode     func() runtime.Object `yaml:"-"`
	ListObjectYamlMode func() runtime.Object `yaml:"-"`

	// Scheme registration function — generated by controller-gen per API type.
	// Go mode: set in BuildKatalogFromGo().
	// YAML mode: resolved by ork generate into initialize/registry.go → RegisterScheme().
	Scheme func(s *runtime.Scheme) error `yaml:"-"`

	// ── Computed GVK/GVR ─────────────────────────────────────────────────────
	// Populated by setGroupVersionKind() during Katalog validation.
	// Derived from APITypes fields — never set manually.
	GroupVersion         *schema.GroupVersion        `yaml:"-"`
	GroupVersionKind     schema.GroupVersionKind     `yaml:"-"`
	GroupVersionResource schema.GroupVersionResource `yaml:"-"`

	// ── Scope ─────────────────────────────────────────────────────────────────
	Namespaced bool   `yaml:"namespaced"`
	Namespace  string `yaml:"namespace" validate:"omitempty"`

	// ── Runtime behaviour ─────────────────────────────────────────────────────
	Workers   int           `yaml:"workers" validate:"omitempty,gte=1,lte=50"`
	Resync    time.Duration `yaml:"resync" validate:"omitempty"`
	DependsOn []string      `yaml:"dependsOn"`

	// ── Reconciler + Queue ────────────────────────────────────────────────────
	ReconcilerConfig ReconcilerConfig `yaml:"reconciler"`
	Queue            Queue            `yaml:"queue"`
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// GetRuntimeObjects returns the correct object and list for the given mode.
// YAML mode uses ObjectYamlMode/ListObjectYamlMode populated by addRuntimeObjects().
// Go mode uses ObjectGoMode/ListObjectGoMode set in BuildKatalogFromGo().
func (c *CRDEntry) GetRuntimeObjects(mode string) (runtime.Object, runtime.Object) {
	if mode == "yaml" {
		return c.ObjectYamlMode(), c.ListObjectYamlMode()
	}
	return c.ObjectGoMode, c.ListObjectGoMode
}

// SetMaxQueueDepth returns the per-CRD depth if set, otherwise the Orkestra default.
func (c *CRDEntry) SetMaxQueueDepth(def int) int {
	if c.Queue.MaxQueueDepth == 0 {
		return def
	}
	return c.Queue.MaxQueueDepth
}

// SeWorkers returns the per-CRD depth if set, otherwise the Orkestra default.
func (c *CRDEntry) SetWorkers(def int) int {
	if c.Workers == 0 {
		return def
	}
	return c.Workers
}

// GVK returns the computed GroupVersionKind — shorthand for use in logging and routing.
func (c *CRDEntry) GVK() schema.GroupVersionKind {
	return c.GroupVersionKind
}

// GVR returns the computed GroupVersionResource — used for dynamic client patch calls.
func (c *CRDEntry) GVR() schema.GroupVersionResource {
	return c.GroupVersionResource
}
