// pkg/generate/hooks_generator.go
package generate

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
	"time"

	orktypes "github.com/ialexeze/orkestra/pkg/types"
	"github.com/ialexeze/orkestra/pkg/utils"
)

var hooksTemplate = template.Must(template.New("hooks").Parse(`// pkg/runtime/generated_runtime_hooks.go
// Code generated by "ork generate runtime" on {{ .Timestamp }}. DO NOT EDIT.
// Re-generate by running: ork generate runtime --katalog <path-or-url>
package runtime

import (
	"context"
	"fmt"
	"github.com/ialexeze/orkestra/domain"
	"github.com/ialexeze/orkestra/pkg/kubeclient"
	orktmpl "github.com/ialexeze/orkestra/pkg/orkestra-registry/template"
	orktypes "github.com/ialexeze/orkestra/pkg/types"
{{ if or .NeedsDeployments .NeedsPods }}	
 "strconv"
 orkdeploy "github.com/ialexeze/orkestra/pkg/orkestra-registry/deployments"
{{ end }}{{ if .NeedsServices }}	orksvc "github.com/ialexeze/orkestra/pkg/orkestra-registry/services"
{{ end }}{{ if .NeedsPods }}	orkpods "github.com/ialexeze/orkestra/pkg/orkestra-registry/pods"
{{ end }}{{ if .NeedsJobs }}	orkjobs "github.com/ialexeze/orkestra/pkg/orkestra-registry/jobs"
{{ end }}{{ if .NeedsSecrets }} orksecrets "github.com/ialexeze/orkestra/pkg/orkestra-registry/secrets"
{{ end }}{{ if .NeedsConfigMaps }} orkcm "github.com/ialexeze/orkestra/pkg/orkestra-registry/configmaps"
{{ end }}	"k8s.io/apimachinery/pkg/runtime/schema"
)

func init() {
{{ range .HookCRDs }}	registerTemplateHooks{{ .FuncSuffix }}()
{{ end }}}

{{ range .HookCRDs }}
{{- $crd := . }}
func registerTemplateHooks{{ .FuncSuffix }}() {
	orktypes.HookRegistry[schema.GroupVersionKind{
		Group:   "{{ .Group }}",
		Version: "{{ .Version }}",
		Kind:    "{{ .Kind }}",
	}] = func() domain.AnyReconcileHooks {
		return domain.ReconcileHooks[domain.Object]{
			OnReconcile: {{ .FuncSuffix }}OnReconcile,
			OnDelete:    {{ .FuncSuffix }}OnDelete,
		}
	}
}

func {{ .FuncSuffix }}OnReconcile(ctx context.Context, obj domain.Object) error {
	kube, ok := kubeclient.FromContext(ctx)
	if !ok || kube == nil {
		return fmt.Errorf("{{ .Name }}: kubeclient not found in context")
	}

	resolver, err := orktmpl.NewResolver(ctx, obj)
	if err != nil {
		return fmt.Errorf("{{ .Name }}: resolver: %w", err)
	}
	_ = resolver
{{ range .OnCreateDeployments }}
	// Deployment[{{ .Index }}]: onCreate — idempotent create
	{
		resolved, err := resolver.ResolveDeploymentTemplate(orktypes.DeploymentTemplateSource{
			Name:        {{ .Name }},
			Image:       {{ .Image }},
			Replicas:    {{ .Replicas }},
			Port:        {{ .Port }},
			Namespace:   {{ .Namespace }},
			Labels:      []orktypes.ResourceLabel{ {{ range .Labels }}{Key: {{ .Key }}, Value: {{ .Value }}},{{ end }} },
			Annotations: []orktypes.ResourceLabel{ {{ range .Annotations }}{Key: {{ .Key }}, Value: {{ .Value }}},{{ end }} },
			Resources:   {{ .Resources }},
		})
		if err != nil {
			return fmt.Errorf("{{ $crd.Name }}: deployment[{{ .Index }}]: %w", err)
		}
		staticReplicas, _ := strconv.Atoi({{ .StaticReplicas }})
		spec := orkdeploy.Resolve(resolved, staticReplicas, resolver.OwnerName())
		if err := orkdeploy.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("{{ $crd.Name }}: deployment[{{ .Index }}].create: %w", err)
		}
	}
{{ end }}
{{ range .OnReconcileDeployments }}
	// Deployment[{{ .Index }}]: onReconcile — drift correction
	{
		resolved, err := resolver.ResolveDeploymentTemplate(orktypes.DeploymentTemplateSource{
			Name:        {{ .Name }},
			Image:       {{ .Image }},
			Replicas:    {{ .Replicas }},
			Port:        {{ .Port }},
			Namespace:   {{ .Namespace }},
			Labels:      []orktypes.ResourceLabel{ {{ range .Labels }}{Key: {{ .Key }}, Value: {{ .Value }}},{{ end }} },
			Annotations: []orktypes.ResourceLabel{ {{ range .Annotations }}{Key: {{ .Key }}, Value: {{ .Value }}},{{ end }} },
			Resources:   {{ .Resources }},
		})
		if err != nil {
			return fmt.Errorf("{{ $crd.Name }}: onReconcile deployment[{{ .Index }}]: %w", err)
		}
		staticReplicas, _ := strconv.Atoi({{ .StaticReplicas }})
		spec := orkdeploy.Resolve(resolved, staticReplicas, resolver.OwnerName())
		if err := orkdeploy.Update(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("{{ $crd.Name }}: onReconcile deployment[{{ .Index }}].update: %w", err)
		}
	}
{{ end }}
{{ range .OnCreateServices }}
	// Service[{{ .Index }}]: onCreate
	{
		resolved, err := resolver.ResolveServiceTemplate(orktypes.ServiceTemplateSource{
			Name:       {{ .Name }},
			Type:       {{ .Type }},
			Port:       {{ .Port }},
			TargetPort: {{ .TargetPort }},
			Namespace:  {{ .Namespace }},
			Labels:     []orktypes.ResourceLabel{ {{ range .Labels }}{Key: {{ .Key }}, Value: {{ .Value }}},{{ end }} },
		})
		if err != nil {
			return fmt.Errorf("{{ $crd.Name }}: service[{{ .Index }}]: %w", err)
		}
		spec := orksvc.Resolve(resolved, resolver.OwnerName())
		if err := orksvc.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("{{ $crd.Name }}: service[{{ .Index }}].create: %w", err)
		}
	}
{{ end }}
{{ range .OnReconcileServices }}
	// Service[{{ .Index }}]: onReconcile
	{
		resolved, err := resolver.ResolveServiceTemplate(orktypes.ServiceTemplateSource{
			Name:       {{ .Name }},
			Type:       {{ .Type }},
			Port:       {{ .Port }},
			TargetPort: {{ .TargetPort }},
			Namespace:  {{ .Namespace }},
			Labels:     []orktypes.ResourceLabel{ {{ range .Labels }}{Key: {{ .Key }}, Value: {{ .Value }}},{{ end }} },
		})
		if err != nil {
			return fmt.Errorf("{{ $crd.Name }}: onReconcile service[{{ .Index }}]: %w", err)
		}
		spec := orksvc.Resolve(resolved, resolver.OwnerName())
		if err := orksvc.Update(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("{{ $crd.Name }}: onReconcile service[{{ .Index }}].update: %w", err)
		}
	}
{{ end }}
{{ range .OnCreateSecrets }}
    // Secret[{{ .Index }}]: onCreate
    {
        resolved, err := resolver.ResolveSecretTemplate(orktypes.SecretTemplateSource{
            Name:          {{ .Name }},
            Namespace:     {{ .Namespace }},
            Type:          {{ .Type }},
            FromSecret:    {{ .FromSecret }},
            FromNamespace: {{ .FromNamespace }},
            Data:          map[string]string{ {{ range $k, $v := .Data }}{{ printf "%q:%s," $k $v }}{{ end }} },
            ToNamespaces:  []string{ {{ range .ToNamespaces }}{{ . }},{{ end }} },
        })
        if err != nil {
            return fmt.Errorf("{{ $crd.Name }}: secret[{{ .Index }}]: %w", err)
        }
		spec := orksecrets.Resolve(resolved, resolver.OwnerName())
		if err := orksecrets.Create(ctx, kube, obj, spec); err != nil {
            return fmt.Errorf("{{ $crd.Name }}: secret[{{ .Index }}].create: %w", err)
        }
    }
{{ end }}
{{ range .OnReconcileSecrets }}
    // Secret[{{ .Index }}]: onReconcile
    {
        resolved, err := resolver.ResolveSecretTemplate(orktypes.SecretTemplateSource{
            Name:          {{ .Name }},
            Namespace:     {{ .Namespace }},
            Type:          {{ .Type }},
            FromSecret:    {{ .FromSecret }},
            FromNamespace: {{ .FromNamespace }},
            Data:          map[string]string{ {{ range $k, $v := .Data }}{{ printf "%q:%s," $k $v }}{{ end }} },
            ToNamespaces:  []string{ {{ range .ToNamespaces }}{{ . }},{{ end }} },
        })
        if err != nil {
            return fmt.Errorf("{{ $crd.Name }}: secret[{{ .Index }}]: %w", err)
        }
		spec := orksecrets.Resolve(resolved, resolver.OwnerName())
		if err := orksecrets.Update(ctx, kube, obj, spec); err != nil {
            return fmt.Errorf("{{ $crd.Name }}: secret[{{ .Index }}].update: %w", err)
        }
    }
{{ end }}
{{ range .OnCreateConfigMaps }}
    // ConfigMap[{{ .Index }}]: onCreate
    {
        resolved, err := resolver.ResolveConfigMapTemplate(orktypes.ConfigMapTemplateSource{
            Name:          {{ .Name }},
            Namespace:     {{ .Namespace }},
            FromConfigMap: {{ .FromConfigMap }},
            FromNamespace: {{ .FromNamespace }},
            Data:          map[string]string{ {{ range $k, $v := .Data }}{{ printf "%q:%s," $k $v }}{{ end }} },
            ToNamespaces:  []string{ {{ range .ToNamespaces }}{{ . }},{{ end }} },
        })
        if err != nil {
            return fmt.Errorf("{{ $crd.Name }}: configmap[{{ .Index }}]: %w", err)
        }
		spec := orkcm.Resolve(resolved, resolver.OwnerName())
		if err := orkcm.Create(ctx, kube, obj, spec); err != nil {
            return fmt.Errorf("{{ $crd.Name }}: configmap[{{ .Index }}].create: %w", err)
        }
    }
{{ end }}
{{ range .OnReconcileConfigMaps }}
    // ConfigMap[{{ .Index }}]: onReconcile
    {
        resolved, err := resolver.ResolveConfigMapTemplate(orktypes.ConfigMapTemplateSource{
            Name:          {{ .Name }},
            Namespace:     {{ .Namespace }},
            FromConfigMap: {{ .FromConfigMap }},
            FromNamespace: {{ .FromNamespace }},
            Data:          map[string]string{ {{ range $k, $v := .Data }}{{ printf "%q:%s," $k $v }}{{ end }} },
            ToNamespaces:  []string{ {{ range .ToNamespaces }}{{ . }},{{ end }} },
        })
        if err != nil {
            return fmt.Errorf("{{ $crd.Name }}: configmap[{{ .Index }}]: %w", err)
        }
		spec := orkcm.Resolve(resolved, resolver.OwnerName())
		if err := orkcm.Update(ctx, kube, obj, spec); err != nil {
            return fmt.Errorf("{{ $crd.Name }}: configmap[{{ .Index }}].update: %w", err)
        }
    }
{{ end }}
return nil
}

func {{ .FuncSuffix }}OnDelete(ctx context.Context, obj domain.Object) error {
{{ if .HasOnDelete }}	kube, ok := kubeclient.FromContext(ctx)
	if !ok || kube == nil {
		return fmt.Errorf("{{ .Name }}: kubeclient not found in context")
	}

	resolver, err := orktmpl.NewResolver(ctx, obj)
	if err != nil {
		return fmt.Errorf("{{ .Name }}: resolver: %w", err)
	}
	_ = resolver
{{ range .OnDeleteJobs }}
	// Job[{{ .Index }}]: onDelete cleanup
	{
		resolved, err := resolver.ResolveJobTemplate(orktypes.JobTemplateSource{
			Name:      {{ .Name }},
			Image:     {{ .Image }},
			Namespace: {{ .Namespace }},
			Command:   []string{ {{ range .Command }}{{ . }},{{ end }} },
		})
		if err != nil {
			return fmt.Errorf("{{ $crd.Name }}: onDelete job[{{ .Index }}]: %w", err)
		}
		spec := orkjobs.Resolve(resolved, {{ .BackoffLimit }}, resolver.OwnerName())
		if err := orkjobs.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("{{ $crd.Name }}: onDelete job[{{ .Index }}].create: %w", err)
		}
	}
{{ end }}	return nil
{{ else }}	// No explicit onDelete templates — owner references handle cleanup automatically.
	return nil
{{ end }}}
{{ end }}`))

// ── Template data ─────────────────────────────────────────────────────────────

type hooksTemplateData struct {
	Timestamp        string
	NeedsDeployments bool
	NeedsServices    bool
	NeedsPods        bool
	NeedsJobs        bool
	NeedsSecrets     bool
	NeedsConfigMaps  bool
	HookCRDs         []hookCRDData
}

type hookCRDData struct {
	Name        string
	FuncSuffix  string
	Group       string
	Version     string
	Kind        string
	HasOnDelete bool

	// Deployments
	OnCreateDeployments    []deploymentTemplateData
	OnReconcileDeployments []deploymentTemplateData

	// Services
	OnCreateServices    []serviceTemplateData
	OnReconcileServices []serviceTemplateData

	// Jobs
	OnDeleteJobs []jobTemplateData

	// Secrets
	OnCreateSecrets    []secretTemplateData
	OnReconcileSecrets []secretTemplateData
	OnDeleteSecrets    []secretTemplateData

	// ConfigMaps
	OnCreateConfigMaps    []configMapTemplateData
	OnReconcileConfigMaps []configMapTemplateData
	OnDeleteConfigMaps    []configMapTemplateData
}

type deploymentTemplateData struct {
	Index          int
	Name           string
	Image          string
	Replicas       string
	Port           string
	Namespace      string
	StaticReplicas string
	Resources      string
	Labels         []labelGoData
	Annotations    []labelGoData
}

type serviceTemplateData struct {
	Index      int
	Name       string
	Type       string
	Port       string
	TargetPort string
	Namespace  string
	Labels     []labelGoData
}

type jobTemplateData struct {
	Index        int
	Name         string
	Image        string
	Namespace    string
	Command      []string
	BackoffLimit string
}

type labelGoData struct {
	Key   string
	Value string
}

type secretTemplateData struct {
	Index         int
	Name          string
	Namespace     string
	ToNamespaces  []string
	FromSecret    string
	FromNamespace string
	Data          map[string]string
	Type          string
}

type configMapTemplateData struct {
	Index         int
	Name          string
	Namespace     string
	ToNamespaces  []string
	FromConfigMap string
	FromNamespace string
	Data          map[string]string
	Type          string
}

// ── Hooks ─────────────────────────────────────────────────────────────────────

func Hooks(katalogPath string, dryRun bool) error {
	data, err := utils.LoadFile(katalogPath)
	if err != nil {
		return fmt.Errorf("loading katalog from %q: %w", katalogPath, err)
	}

	kat, err := parseKatalog(data)
	if err != nil {
		return err
	}

	var hookCRDs []hookCRDData
	needsDeployments, needsServices, needsPods, needsJobs, needsSecrets, needsConfigMaps := false, false, false, false, false, false

	for _, crd := range kat.Spec.CRDs {
		if !crd.Enabled || !crd.HasTemplates() {
			continue
		}
		if !crd.IsDynamic() {
			return fmt.Errorf(
				"CRD %q: declarative templates require reconciler.mode: dynamic",
				crd.Name,
			)
		}

		crdData, err := buildHookCRDData(crd)
		if err != nil {
			return fmt.Errorf("CRD %q: %w", crd.Name, err)
		}

		if len(crdData.OnCreateDeployments) > 0 || len(crdData.OnReconcileDeployments) > 0 {
			needsDeployments = true
		}
		if len(crdData.OnCreateServices) > 0 {
			needsServices = true
		}
		if len(crdData.OnDeleteJobs) > 0 {
			needsJobs = true
		}
		if len(crdData.OnCreateSecrets) > 0 || len(crdData.OnReconcileSecrets) > 0 {
			needsSecrets = true
		}
		if len(crdData.OnCreateConfigMaps) > 0 || len(crdData.OnReconcileConfigMaps) > 0 {
			needsConfigMaps = true
		}

		_ = needsPods // pods handled in future iteration

		hookCRDs = append(hookCRDs, crdData)
	}

	if len(hookCRDs) == 0 {
		return nil
	}

	// Add to template Data
	tmplData := hooksTemplateData{
		Timestamp:        time.Now().UTC().Format(time.RFC3339),
		NeedsDeployments: needsDeployments,
		NeedsServices:    needsServices,
		NeedsPods:        needsPods,
		NeedsJobs:        needsJobs,
		NeedsSecrets:     needsSecrets,
		NeedsConfigMaps:  needsConfigMaps,
		HookCRDs:         hookCRDs,
	}

	outPath := filepath.Join(RuntimePackage, HooksFile)
	return renderTemplateToFile(hooksTemplate, tmplData, outPath, true, dryRun)
}

// ── Data builders ─────────────────────────────────────────────────────────────

func buildHookCRDData(crd orktypes.CRDEntry) (hookCRDData, error) {
	rc := crd.ReconcilerConfig
	data := hookCRDData{
		Name:       crd.Name,
		FuncSuffix: toFuncSuffix(crd.Name),
		Group:      crd.APITypes.Group,
		Version:    crd.APITypes.Version,
		Kind:       crd.APITypes.Kind,
	}

	if rc.OnCreate != nil {
		// Deployments
		deps, err := buildDeploymentData(rc.OnCreate.Deployments)
		if err != nil {
			return data, fmt.Errorf("onCreate.deployments: %w", err)
		}
		data.OnCreateDeployments = deps

		// Auto-generate onReconcile entries for deployments with reconcile: true
		// Only if onReconcile.deployments is not explicitly declared
		if rc.OnReconcile == nil || len(rc.OnReconcile.Deployments) == 0 {
			for _, src := range rc.OnCreate.Deployments {
				if src.Reconcile {
					reconcileDeps, err := buildDeploymentData([]orktypes.DeploymentTemplateSource{src})
					if err != nil {
						return data, fmt.Errorf("onCreate.deployments[reconcile:true]: %w", err)
					}
					data.OnReconcileDeployments = append(data.OnReconcileDeployments, reconcileDeps...)
				}
			}
		}

		// Services
		svcs, err := buildServiceData(rc.OnCreate.Services)
		if err != nil {
			return data, fmt.Errorf("onCreate.services: %w", err)
		}
		data.OnCreateServices = svcs

		// Auto-generate onReconcile entries for services with reconcile: true
		// Only if onReconcile.services is not explicitly declared
		if rc.OnReconcile == nil || len(rc.OnReconcile.Services) == 0 {
			for _, src := range rc.OnCreate.Services {
				if src.Reconcile {
					reconcileSvcs, err := buildServiceData([]orktypes.ServiceTemplateSource{src})
					if err != nil {
						return data, fmt.Errorf("onCreate.services[reconcile:true]: %w", err)
					}
					data.OnReconcileServices = append(data.OnReconcileServices, reconcileSvcs...)
				}
			}
		}

		// Secrets
		secrets, err := buildSecretData(rc.OnCreate.Secrets)
		if err != nil {
			return data, fmt.Errorf("onCreate.secrets: %w", err)
		}
		data.OnCreateSecrets = secrets

		// Auto-generate onReconcile entries for secrets with reconcile: true
		// Only if onReconcile.secrets is not explicitly declared
		if rc.OnReconcile == nil || len(rc.OnReconcile.Secrets) == 0 {
			for _, src := range rc.OnCreate.Secrets {
				if src.Reconcile {
					reconcileSecrets, err := buildSecretData([]orktypes.SecretTemplateSource{src})
					if err != nil {
						return data, fmt.Errorf("onCreate.secrets[reconcile:true]: %w", err)
					}
					data.OnReconcileSecrets = append(data.OnReconcileSecrets, reconcileSecrets...)
				}
			}
		}

		// ConfigMaps
		configMaps, err := buildConfigMapData(rc.OnCreate.ConfigMaps)
		if err != nil {
			return data, fmt.Errorf("onCreate.configMaps: %w", err)
		}
		data.OnCreateConfigMaps = configMaps

		// Auto-generate onReconcile entries for configMaps with reconcile: true
		// Only if onReconcile.configMaps is not explicitly declared
		if rc.OnReconcile == nil || len(rc.OnReconcile.ConfigMaps) == 0 {
			for _, src := range rc.OnCreate.ConfigMaps {
				if src.Reconcile {
					reconcileConfigMaps, err := buildConfigMapData([]orktypes.ConfigMapTemplateSource{src})
					if err != nil {
						return data, fmt.Errorf("onCreate.configMaps[reconcile:true]: %w", err)
					}
					data.OnReconcileConfigMaps = append(data.OnReconcileConfigMaps, reconcileConfigMaps...)
				}
			}
		}
	}

	// OnReconcile
	//
	// Deployments
	if rc.OnReconcile != nil {
		deps, err := buildDeploymentData(rc.OnReconcile.Deployments)
		if err != nil {
			return data, fmt.Errorf("onReconcile.deployments: %w", err)
		}
		data.OnReconcileDeployments = deps
	}

	// Secrets
	if rc.OnReconcile != nil {
		secrets, err := buildSecretData(rc.OnReconcile.Secrets)
		if err != nil {
			return data, fmt.Errorf("onReconcile.secrets: %w", err)
		}
		data.OnReconcileSecrets = secrets
	}

	// ConfigMaps
	if rc.OnReconcile != nil {
		configMaps, err := buildConfigMapData(rc.OnReconcile.ConfigMaps)
		if err != nil {
			return data, fmt.Errorf("onReconcile.configMaps: %w", err)
		}
		data.OnReconcileConfigMaps = configMaps
	}

	// OnDelete
	//
	// Jobs
	if rc.OnDelete != nil {
		jobs, err := buildJobData(rc.OnDelete.Jobs)
		if err != nil {
			return data, fmt.Errorf("onDelete.jobs: %w", err)
		}
		data.OnDeleteJobs = jobs
		data.HasOnDelete = len(jobs) > 0
	}

	// Secrets
	if rc.OnDelete != nil {
		secrets, err := buildSecretData(rc.OnDelete.Secrets)
		if err != nil {
			return data, fmt.Errorf("onDelete.secrets: %w", err)
		}
		data.OnDeleteSecrets = secrets

	}

	return data, nil
}

func buildDeploymentData(srcs []orktypes.DeploymentTemplateSource) ([]deploymentTemplateData, error) {
	var result []deploymentTemplateData
	for i, src := range srcs {
		if src.Image == "" {
			return nil, fmt.Errorf("deployment[%d]: image is required", i)
		}

		dd := deploymentTemplateData{
			Index:     i,
			Name:      goLit(src.Name),
			Image:     goLit(src.Image),
			Replicas:  goLit(src.Replicas),
			Port:      goLit(src.Port),
			Namespace: goLit(src.Namespace),
			Resources: resourcesGoLit(src.Resources),
		}

		if src.Replicas != "" && !strings.Contains(src.Replicas, "{{") {
			if _, err := strconv.Atoi(src.Replicas); err == nil {
				dd.StaticReplicas = fmt.Sprintf("%q", src.Replicas)
			}
		}
		if dd.StaticReplicas == "" {
			dd.StaticReplicas = `"1"`
		}

		for _, l := range src.Labels {
			dd.Labels = append(dd.Labels, labelGoData{Key: goLit(l.Key), Value: goLit(l.Value)})
		}
		for _, a := range src.Annotations {
			dd.Annotations = append(dd.Annotations, labelGoData{Key: goLit(a.Key), Value: goLit(a.Value)})
		}

		result = append(result, dd)
	}
	return result, nil
}

func buildServiceData(srcs []orktypes.ServiceTemplateSource) ([]serviceTemplateData, error) {
	var result []serviceTemplateData
	for i, src := range srcs {
		sd := serviceTemplateData{
			Index:      i,
			Name:       goLit(src.Name),
			Type:       goLit(src.Type),
			Port:       goLit(src.Port),
			TargetPort: goLit(src.TargetPort),
			Namespace:  goLit(src.Namespace),
		}
		for _, l := range src.Labels {
			sd.Labels = append(sd.Labels, labelGoData{Key: goLit(l.Key), Value: goLit(l.Value)})
		}
		result = append(result, sd)
	}
	return result, nil
}

func buildJobData(srcs []orktypes.JobTemplateSource) ([]jobTemplateData, error) {
	var result []jobTemplateData
	for i, src := range srcs {
		if src.Image == "" {
			return nil, fmt.Errorf("job[%d]: image is required", i)
		}
		jd := jobTemplateData{
			Index:        i,
			Name:         goLit(src.Name),
			Image:        goLit(src.Image),
			Namespace:    goLit(src.Namespace),
			BackoffLimit: fmt.Sprintf("%d", src.BackoffLimit),
		}
		for _, c := range src.Command {
			jd.Command = append(jd.Command, goLit(c))
		}
		result = append(result, jd)
	}
	return result, nil
}
func buildSecretData(srcs []orktypes.SecretTemplateSource) ([]secretTemplateData, error) {
	var result []secretTemplateData

	for i, src := range srcs {
		if src.Name == "" {
			return nil, fmt.Errorf("secret[%d]: name is required", i)
		}

		sd := secretTemplateData{
			Index:         i,
			Name:          goLit(src.Name),
			Namespace:     goLit(src.Namespace),
			FromSecret:    goLit(src.FromSecret),
			FromNamespace: goLit(src.FromNamespace),
			Type:          goLit(src.Type),
		}

		for _, ns := range src.ToNamespaces {
			sd.ToNamespaces = append(sd.ToNamespaces, goLit(ns))
		}

		// static data map
		if len(src.Data) > 0 {
			sd.Data = make(map[string]string)
			for k, v := range src.Data {
				sd.Data[k] = goLit(v)
			}
		}

		result = append(result, sd)
	}

	return result, nil
}

func buildConfigMapData(srcs []orktypes.ConfigMapTemplateSource) ([]configMapTemplateData, error) {
	var result []configMapTemplateData

	for i, src := range srcs {
		if src.Name == "" {
			return nil, fmt.Errorf("configmap[%d]: name is required", i)
		}

		cd := configMapTemplateData{
			Index:         i,
			Name:          goLit(src.Name),
			Namespace:     goLit(src.Namespace),
			FromConfigMap: goLit(src.FromConfigMap),
			FromNamespace: goLit(src.FromNamespace),
		}

		for _, ns := range src.ToNamespaces {
			cd.ToNamespaces = append(cd.ToNamespaces, goLit(ns))
		}

		if len(src.Data) > 0 {
			cd.Data = make(map[string]string)
			for k, v := range src.Data {
				cd.Data[k] = goLit(v)
			}
		}

		result = append(result, cd)
	}

	return result, nil
}

// ── String helpers ────────────────────────────────────────────────────────────

func goLit(s string) string {
	if s == "" {
		return `""`
	}
	return fmt.Sprintf("%q", s)
}

func resourcesGoLit(r *orktypes.ResourceRequirements) string {
	if r == nil {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("&orktypes.ResourceRequirements{")
	if len(r.Requests) > 0 {
		b.WriteString("Requests: map[string]string{")
		for k, v := range r.Requests {
			b.WriteString(fmt.Sprintf("%q:%q,", k, v))
		}
		b.WriteString("},")
	}
	if len(r.Limits) > 0 {
		b.WriteString("Limits: map[string]string{")
		for k, v := range r.Limits {
			b.WriteString(fmt.Sprintf("%q:%q,", k, v))
		}
		b.WriteString("},")
	}
	b.WriteString("}")
	return b.String()
}

func toFuncSuffix(name string) string {
	parts := strings.Split(name, "-")
	var b strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return b.String()
}
