// pkg/generate/registry_generator.go
package generate

import (
	"fmt"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/ialexeze/orkestra/pkg/merger"
	orktypes "github.com/ialexeze/orkestra/pkg/types"
)

// registryTemplate emits zz_generated_runtime_registry.go.
//
// This file registers compiled Go types and external functions into the
// package-level registries in pkg/types so Orkestra can wire them at startup.
//
// What gets registered and why:
//
//	ObjectRegistry / ListRegistry
//	  Required when apiTypes.location is set (typed CRDs).
//	  The informer and REST client need factory functions that return the
//	  correct concrete Go type for a given GVK. Without these, the REST client
//	  cannot decode API server responses into Go structs.
//
//	HookRegistry
//	  Required when reconciler.hooks is declared.
//	  The hook function lives in an external package. The generator writes the
//	  import and a closure that calls the user's function. addHooks() reads
//	  this registry at startup and sets HookFactory on the CRD entry.
//
//	ReconcilerRegistry
//	  Required when reconciler.default: false and reconciler.constructor is declared.
//	  Same pattern as HookRegistry — external function, import + closure.
//
//	RegisterTypedScheme
//	  Called by NewSchemeRegistry for typed CRDs.
//	  Each compiled API type package exports AddToScheme. This calls them all.
//	  Not needed for dynamic CRDs — they use *unstructured.Unstructured which
//	  the scheme already knows about.
//
// What does NOT get registered here:
//
//	Dynamic template CRDs (onCreate/onReconcile/onDelete blocks)
//	  These are handled entirely at runtime by GenericReconciler.runTemplateReconcile().
//	  No registration needed. No generated file needed. ork generate runtime
//	  is not required for pure dynamic operators.
var registryTemplate = template.Must(template.New("registry").Parse(`// pkg/runtime/zz_generated_runtime_registry.go
// Code generated by "ork generate runtime" on {{ .Timestamp }}. DO NOT EDIT.
// Re-generate by running: ork generate runtime --katalog <path-or-url>
//
// This file registers compiled Go types and external functions.
// Dynamic template CRDs do not appear here — they are handled at runtime
// by GenericReconciler without any code generation.
package runtime

import (
	"fmt"

	orktypes "github.com/ialexeze/orkestra/pkg/types"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	{{ if or .NeedsHookImports .NeedsRecImports }}"github.com/ialexeze/orkestra/domain"
	{{ end }}{{ if .NeedsRecImports }}"github.com/ialexeze/orkestra/pkg/kubeclient"
	"github.com/ialexeze/orkestra/pkg/event"
	"k8s.io/client-go/tools/cache"
	{{ end }}
{{ range .Imports }}	{{ .Alias }} "{{ .Location }}"
{{ end }})

// RegisterRuntimeObjects populates ObjectRegistry, ListRegistry, HookRegistry,
// and ReconcilerRegistry. Called once at startup before Katalog validation.
//
// Object/List entries — factory functions for typed CRDs.
//   Used by the informer to create zero-value instances for cache storage
//   and type assertion during reconciliation.
//
// Hook entries — factory functions for Go hook implementations.
//   Called by addHooks() during Katalog validation to wire HookFactory
//   onto the CRD entry. GenericReconciler calls HookFactory() once at
//   startCRDWorkers time to obtain the typed hooks.
//
// Reconciler entries — constructor functions for custom reconcilers.
//   Called by addReconcilers() during Katalog validation to wire Constructor
//   onto the CRD entry. DependencyKontroller calls Constructor() once at
//   startCRDWorkers time to build the reconciler.
func RegisterRuntimeObjects() {
{{ range .Entries }}
	// {{ .Kind }} — typed CRD object and list factories
	orktypes.ObjectRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() runtime.Object { return &{{ .Alias }}.{{ .Object }}{} }
	orktypes.ListRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() runtime.Object { return &{{ .Alias }}.{{ .List }}{} }
{{ end }}
{{ if .HookEntries }}{{ range .HookEntries }}
	// {{ .Kind }} — Go hook factory
	// Calls {{ .Alias }}.{{ .Function }}() to obtain typed ReconcileHooks.
	orktypes.HookRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() domain.AnyReconcileHooks {
			return {{ .Alias }}.{{ .Function }}()
		}
{{ end }}{{ end }}
{{ if .RecEntries }}{{ range .RecEntries }}
	// {{ .Kind }} — custom reconciler constructor
	// Calls {{ .Alias }}.{{ .Function }}() to build the user's reconciler.
	orktypes.ReconcilerRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func(kube *kubeclient.Kubeclient, inf cache.SharedIndexInformer, ev *event.Event) domain.Reconciler {
			return {{ .Alias }}.{{ .Function }}(kube, inf, ev)
		}
{{ end }}{{ end }}}

// RegisterTypedScheme registers the AddToScheme function for each typed CRD.
// Called by NewSchemeRegistry during startup so the REST client can decode
// API server responses into compiled Go structs.
//
// Dynamic CRDs do not appear here — *unstructured.Unstructured is registered
// separately in registerDynamicScheme using AddKnownTypeWithName.
func RegisterTypedScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
{{ range .Entries }}	if err := {{ .Alias }}.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register {{ .Object }} scheme: %w", err)
	}
{{ end }}	return scheme, nil
}
`))

// Runtime generates zz_generated_runtime_registry.go from the merged Katalog.
//
// When generation is needed (and why):
//
//	Typed CRDs (apiTypes.location set)
//	  The compiled Go type must be registered so the informer and REST client
//	  can decode API server responses. Without this, List/Watch calls fail with
//	  "not suitable for converting" errors.
//
//	Go hooks (reconciler.hooks declared)
//	  The hook function lives in an external package. The generator writes the
//	  import and wires it into HookRegistry so addHooks() can find it.
//
//	Custom constructors (reconciler.default: false)
//	  Same as Go hooks — external function needs import and ReconcilerRegistry entry.
//
// When generation is NOT needed:
//
//	Dynamic template CRDs (only onCreate/onReconcile/onDelete declared)
//	  GenericReconciler.runTemplateReconcile() reads the Katalog's ReconcilerConfig
//	  directly at runtime and calls the OrkestraRegistry functions itself.
//	  No generated file. No ork generate runtime. Just ork run.
func Runtime(m *merger.Merger, dryRun bool) error {
	crds := m.All()

	var (
		imports     []importEntry
		entries     []registryEntry   // typed CRDs → ObjectRegistry + ListRegistry + RegisterTypedScheme
		hookEntries []hookEntry       // Go hooks → HookRegistry
		recEntries  []reconcilerEntry // custom constructors → ReconcilerRegistry

		seenObjectAliases = map[string]string{}
		seenHookAliases   = map[string]string{}
		seenRecAliases    = map[string]string{}
	)

	for _, crd := range crds {
		if !crd.IsEnabled() {
			continue
		}

		// ── Typed CRDs ────────────────────────────────────────────────────────
		// apiTypes.location set means compiled Go types exist.
		// We need ObjectRegistry + ListRegistry entries so the informer can
		// create zero-value instances, and RegisterTypedScheme so the REST
		// client can decode API server responses.
		//
		// Dynamic CRDs (no location) skip this entirely — they use the dynamic
		// client which bypasses scheme decoding.
		if !crd.IsDynamic() && crd.APITypes.Location != "" {
			if err := validateAPITypes(crd); err != nil {
				return fmt.Errorf("CRD %q: %w", crd.Name, err)
			}

			alias := resolveAlias(crd.APITypes.Alias, crd.Name, crd.APITypes.Location)

			if err := dedupeImport(seenObjectAliases, alias, crd.APITypes.Location, crd.Name); err != nil {
				return err
			}
			if _, seen := seenObjectAliases[alias]; !seen {
				imports = append(imports, importEntry{Alias: alias, Location: crd.APITypes.Location})
				seenObjectAliases[alias] = crd.APITypes.Location
			}

			entries = append(entries, registryEntry{
				Alias:   alias,
				Object:  crd.APITypes.Object,
				List:    crd.APITypes.List,
				Group:   crd.APITypes.Group,
				Version: crd.APITypes.Version,
				Kind:    crd.APITypes.Kind,
			})
		}

		// ── Go hooks ──────────────────────────────────────────────────────────
		// reconciler.hooks.location + function declared means the user has
		// written a Go hook function in an external package.
		// We need to import that package and register a closure in HookRegistry
		// so addHooks() can wire it at startup.
		//
		// This is NOT needed for declarative template CRDs — those are handled
		// at runtime by GenericReconciler.runTemplateReconcile() with no
		// registration required.
		if crd.DefaultReconcile() && crd.ReconcilerConfig.Hooks != nil {
			h := crd.ReconcilerConfig.Hooks

			if err := validateHookEntry(h, crd.Name); err != nil {
				return err
			}

			hookAlias := resolveAlias(h.Alias, crd.Name+"hooks", h.Location)

			if err := dedupeImport(seenHookAliases, hookAlias, h.Location, crd.Name); err != nil {
				return err
			}
			if _, seen := seenHookAliases[hookAlias]; !seen {
				imports = append(imports, importEntry{Alias: hookAlias, Location: h.Location})
				seenHookAliases[hookAlias] = h.Location
			}

			hookEntries = append(hookEntries, hookEntry{
				Alias:    hookAlias,
				Function: h.Function,
				Group:    crd.APITypes.Group,
				Version:  crd.APITypes.Version,
				Kind:     crd.APITypes.Kind,
			})
		}

		// ── Custom constructors ───────────────────────────────────────────────
		// reconciler.default: false means the user owns the entire reconcile loop.
		// We need to import their constructor and register it in ReconcilerRegistry
		// so addReconcilers() can wire it at startup.
		if !crd.DefaultReconcile() {
			if crd.ReconcilerConfig.ConstructorDecl == nil {
				return fmt.Errorf(
					"CRD %q: reconciler.default is false but no constructor declared — "+
						"add reconciler.constructor with location and function, "+
						"then re-run ork generate runtime",
					crd.Name,
				)
			}

			c := crd.ReconcilerConfig.ConstructorDecl

			if err := validateConstructorEntry(c, crd.Name); err != nil {
				return err
			}

			recAlias := resolveAlias(c.Alias, crd.Name+"rec", c.Location)

			if err := dedupeImport(seenRecAliases, recAlias, c.Location, crd.Name); err != nil {
				return err
			}
			if _, seen := seenRecAliases[recAlias]; !seen {
				imports = append(imports, importEntry{Alias: recAlias, Location: c.Location})
				seenRecAliases[recAlias] = c.Location
			}

			recEntries = append(recEntries, reconcilerEntry{
				Alias:    recAlias,
				Function: c.Function,
				Group:    crd.APITypes.Group,
				Version:  crd.APITypes.Version,
				Kind:     crd.APITypes.Kind,
			})
		}
	}

	// ── Nothing to generate ───────────────────────────────────────────────────
	// Pure dynamic template Katalogs produce zero entries — this is correct.
	// GenericReconciler handles them at runtime. Exit cleanly, no file written.
	if len(entries) == 0 && len(recEntries) == 0 && len(hookEntries) == 0 {
		if !dryRun {
			fmt.Println("nothing to generate — all CRDs use declarative templates " +
				"(interpreted at runtime by GenericReconciler, no generate step needed)")
		}
		return nil
	}

	// ── Render registry file ──────────────────────────────────────────────────
	registryData := registryTemplateData{
		Timestamp:        time.Now().UTC().Format(time.RFC3339),
		Imports:          imports,
		Entries:          entries,
		HookEntries:      hookEntries,
		RecEntries:       recEntries,
		NeedsRecImports:  len(recEntries) > 0,
		NeedsHookImports: len(hookEntries) > 0,
	}

	outPath := filepath.Join(RuntimePackage, RegistryFile)
	return renderTemplateToFile(registryTemplate, registryData, outPath, true, dryRun)
}

// ── Validation helpers ────────────────────────────────────────────────────────

// validateAPITypes checks that all required fields are present for typed CRD registration.
// These fields are needed to generate correct ObjectRegistry entries and scheme imports.
func validateAPITypes(crd orktypes.CRDEntry) error {
	t := crd.APITypes
	var missing []string
	if t.Object == "" {
		missing = append(missing, "apiTypes.object")
	}
	if t.List == "" {
		missing = append(missing, "apiTypes.list")
	}
	if t.Group == "" {
		missing = append(missing, "apiTypes.group")
	}
	if t.Version == "" {
		missing = append(missing, "apiTypes.version")
	}
	if t.Kind == "" {
		missing = append(missing, "apiTypes.kind")
	}
	if t.Location == "" {
		missing = append(missing, "apiTypes.location")
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required apiTypes fields: %s", strings.Join(missing, ", "))
	}
	return nil
}

// validateHookEntry checks that location and function are both declared.
// Both are required to generate a valid import and HookRegistry closure.
func validateHookEntry(h *orktypes.HookDeclaration, crdName string) error {
	var missing []string
	if h.Location == "" {
		missing = append(missing, "reconciler.hooks.location")
	}
	if h.Function == "" {
		missing = append(missing, "reconciler.hooks.function")
	}
	if len(missing) > 0 {
		return fmt.Errorf("CRD %q: missing required hook fields: %s", crdName, strings.Join(missing, ", "))
	}
	return nil
}

// validateConstructorEntry checks that location and function are both declared.
// Both are required to generate a valid import and ReconcilerRegistry closure.
func validateConstructorEntry(c *orktypes.ConstructorDeclaration, crdName string) error {
	var missing []string
	if c.Location == "" {
		missing = append(missing, "reconciler.constructor.location")
	}
	if c.Function == "" {
		missing = append(missing, "reconciler.constructor.function")
	}
	if len(missing) > 0 {
		return fmt.Errorf("CRD %q: missing required constructor fields: %s", crdName, strings.Join(missing, ", "))
	}
	return nil
}

// dedupeImport returns an error if the same alias is used for two different
// import paths. This catches cases where two CRDs in the same Katalog have
// conflicting aliases — the user must set an explicit alias to resolve.
func dedupeImport(seen map[string]string, alias, location, crdName string) error {
	if existing, ok := seen[alias]; ok && existing != location {
		return fmt.Errorf(
			"CRD %q: import alias %q is already used for %q — "+
				"set a unique alias via apiTypes.alias or reconciler.hooks.alias",
			crdName, alias, existing,
		)
	}
	return nil
}

// resolveAlias returns the import alias to use for a package.
// Priority: explicit alias from Katalog → derived from the last two path segments.
//
// Examples:
//
//	location: github.com/myorg/apis/project/v1alpha1 → prefix + "project" + "v1alpha1"
//	location: github.com/myorg/hooks                 → prefix + "hooks"
func resolveAlias(explicitAlias, prefix, location string) string {
	if explicitAlias != "" {
		return explicitAlias
	}
	parts := strings.Split(strings.TrimRight(location, "/"), "/")
	if len(parts) >= 2 {
		return prefix + parts[len(parts)-2] + strings.ReplaceAll(parts[len(parts)-1], ".", "")
	}
	if len(parts) == 1 {
		return prefix + strings.ReplaceAll(parts[0], ".", "")
	}
	return prefix + "v1"
}
