// pkg/generate/registry_generator.go
package generate

import (
	"fmt"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/ialexeze/orkestra/pkg/runtime"
	"github.com/ialexeze/orkestra/pkg/utils"
)

var registryTemplate = template.Must(template.New("registry").Parse(`// pkg/runtime/generated_runtime_registry.go
// Code generated by "ork generate registry" on {{ .Timestamp }}. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
package runtime

import (
	"fmt"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	{{ if or .NeedsHookImports .NeedsRecImports }}
	"github.com/ialexeze/orkestra/domain"
	 {{ end }}{{ if .NeedsRecImports }}
	"github.com/ialexeze/orkestra/pkg/kubeclient"
	"github.com/ialexeze/orkestra/pkg/event"
	"k8s.io/client-go/tools/cache"
{{ end }}
{{ range .Imports }}	{{ .Alias }} "{{ .Location }}"
{{ end }})

func RegisterRuntimeObjects() {
{{ range .Entries }}
	ObjectRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() runtime.Object { return &{{ .Alias }}.{{ .Object }}{} }
	ListRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() runtime.Object { return &{{ .Alias }}.{{ .List }}{} }
{{ end }}{{ if .HookEntries }}
	{{ range .HookEntries }}
	HookRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() domain.AnyReconcileHooks {
			return {{ .Alias }}.{{ .Function }}()
		}
{{ end }}{{ end }}{{ if .RecEntries }}
{{ range .RecEntries }}
	ReconcilerRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func(kube *kubeclient.Kubeclient, inf cache.SharedIndexInformer, ev *event.Event) domain.Reconciler {
			return {{ .Alias }}.{{ .Function }}(kube, inf, ev)
		}
{{ end }}{{ end }}}

func RegisterScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
{{ range .Entries }}	if err := {{ .Alias }}.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register {{ .Object }} scheme: %w", err)
	}
{{ end }}	return scheme, nil
}
`))

func Registry(katalogPath string, dryRun bool) error {
	data, err := utils.LoadFile(katalogPath)
	if err != nil {
		return fmt.Errorf("loading katalog from %q: %w", katalogPath, err)
	}

	kat, err := parseKatalog(data)
	if err != nil {
		return err
	}

	var (
		imports []importEntry
		entries []registryEntry // Object entry
		// schemeEntries []registryEntry // Scheme entry for registration
		hookEntries []hookEntry
		recEntries  []reconcilerEntry

		seenObjectAliases = map[string]string{}
		seenHookAliases   = map[string]string{}
		seenRecAliases    = map[string]string{}
	)

	for _, crd := range kat.Spec.CRDs {
		if !crd.Enabled {
			continue
		}

		// ── 1. Scheme registration — ALL typed CRDs regardless of reconciler type ──
		// The scheme is needed for the REST client to decode API server responses.
		// Applies to both default: true and default: false.
		if !crd.IsUnstructured() && crd.APITypes.Location != "" {
			alias := resolveAlias(crd.APITypes.Alias, crd.Name, crd.APITypes.Location)

			// Ensure the import is registered — may already be present from object entry
			if err := dedupeImport(seenObjectAliases, alias, crd.APITypes.Location, crd.Name); err != nil {
				return err
			}
			if _, seen := seenObjectAliases[alias]; !seen {
				imports = append(imports, importEntry{Alias: alias, Location: crd.APITypes.Location})
				seenObjectAliases[alias] = crd.APITypes.Location
			}

			// ── 3. Input entries  ─────────────────────────────────────────────────
			entries = append(entries, registryEntry{
				Alias: alias, Object: crd.APITypes.Object, List: crd.APITypes.List,
				Group: crd.APITypes.Group, Version: crd.APITypes.Version, Kind: crd.APITypes.Kind,
			})

			// schemeEntries = append(schemeEntries, registryEntry{			// This for future use cases if needed
			// 	Alias:   alias,
			// 	Object:  crd.APITypes.Object,
			// 	Group:   crd.APITypes.Group,
			// 	Version: crd.APITypes.Version,
			// 	Kind:    crd.APITypes.Kind,
			// })
		}

		// ── 3. Handle Default and Unstrcutured mode ─────────────────────────────────────────────────
		if crd.ReconcilerConfig.Default {

			if crd.ReconcilerConfig.Hooks != nil {
				h := crd.ReconcilerConfig.Hooks
				if err := validateHookEntry(h, crd.Name); err != nil {
					return err
				}

				hookAlias := resolveAlias(h.Alias, crd.Name+"hooks", h.Location)
				if err := dedupeImport(seenHookAliases, hookAlias, h.Location, crd.Name); err != nil {
					return err
				}
				if _, seen := seenHookAliases[hookAlias]; !seen {
					imports = append(imports, importEntry{Alias: hookAlias, Location: h.Location})
					seenHookAliases[hookAlias] = h.Location
				}

				hookEntries = append(hookEntries, hookEntry{
					Alias: hookAlias, Function: h.Function,
					Group: crd.APITypes.Group, Version: crd.APITypes.Version, Kind: crd.APITypes.Kind,
				})
			}
		} else {
			if crd.ReconcilerConfig.ConstructorDecl == nil {
				return fmt.Errorf(
					"CRD %q: reconciler.default is false but no constructor declared — "+
						"add reconciler.constructor with location and function, then re-run ork generate registry",
					crd.Name,
				)
			}

			// ── 4. Validation (regardless of mode) ─────────────────────────────────────────────────
			c := crd.ReconcilerConfig.ConstructorDecl
			if err := validateConstructorEntry(c, crd.Name); err != nil {
				return err
			}

			recAlias := resolveAlias(c.Alias, crd.Name+"rec", c.Location)
			if err := dedupeImport(seenRecAliases, recAlias, c.Location, crd.Name); err != nil {
				return err
			}
			if _, seen := seenRecAliases[recAlias]; !seen {
				imports = append(imports, importEntry{Alias: recAlias, Location: c.Location})
				seenRecAliases[recAlias] = c.Location
			}

			recEntries = append(recEntries, reconcilerEntry{
				Alias: recAlias, Function: c.Function,
				Group: crd.APITypes.Group, Version: crd.APITypes.Version, Kind: crd.APITypes.Kind,
			})
		}
	}

	// ── 5. Handle Not found (regardless of mode) ─────────────────────────────────────────────────
	if len(entries) == 0 && len(recEntries) == 0 {
		return fmt.Errorf("no enabled CRDs found — check that at least one CRD has enabled: true")
	}

	// ── 6. Build registry data  ─────────────────────────────────────────────────
	registryData := registryTemplateData{
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Imports:   imports,
		Entries:   entries,
		// SchemeEntries:    schemeEntries,
		HookEntries:      hookEntries,
		RecEntries:       recEntries,
		NeedsRecImports:  len(recEntries) > 0,
		NeedsHookImports: len(hookEntries) > 0,
	}

	// ── 7. Apply the template with registry data  ─────────────────────────────────────────────────
	if err := renderTemplateToFile(registryTemplate, registryData, filepath.Join(RuntimePackage, RegistryFile), true, dryRun); err != nil {
		return err
	}

	return nil
}

func validateAPITypes(crd runtime.CRDEntry) error {
	t := crd.APITypes
	var missing []string
	if t.Object == "" {
		missing = append(missing, "apiTypes.object")
	}
	if t.List == "" {
		missing = append(missing, "apiTypes.list")
	}
	if t.Group == "" {
		missing = append(missing, "apiTypes.group")
	}
	if t.Version == "" {
		missing = append(missing, "apiTypes.version")
	}
	if t.Kind == "" {
		missing = append(missing, "apiTypes.kind")
	}
	if t.Location == "" {
		missing = append(missing, "apiTypes.location")
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required apiTypes fields: %s", strings.Join(missing, ", "))
	}
	return nil
}

func validateHookEntry(h *runtime.HookDeclaration, crdName string) error {
	var missing []string
	if h.Location == "" {
		missing = append(missing, "reconciler.hooks.location")
	}
	if h.Function == "" {
		missing = append(missing, "reconciler.hooks.function")
	}
	if len(missing) > 0 {
		return fmt.Errorf("CRD %q: missing required hook fields: %s", crdName, strings.Join(missing, ", "))
	}
	return nil
}

func validateConstructorEntry(c *runtime.ConstructorDeclaration, crdName string) error {
	var missing []string
	if c.Location == "" {
		missing = append(missing, "reconciler.constructor.location")
	}
	if c.Function == "" {
		missing = append(missing, "reconciler.constructor.function")
	}
	if len(missing) > 0 {
		return fmt.Errorf("CRD %q: missing required constructor fields: %s", crdName, strings.Join(missing, ", "))
	}
	return nil
}

func dedupeImport(seen map[string]string, alias, location, crdName string) error {
	if existing, ok := seen[alias]; ok && existing != location {
		return fmt.Errorf(
			"CRD %q: import alias %q is already used for %q — set a unique alias in the Katalog entry",
			crdName, alias, existing,
		)
	}
	return nil
}

func resolveAlias(explicitAlias, prefix, location string) string {
	if explicitAlias != "" {
		return explicitAlias
	}
	parts := strings.Split(strings.TrimRight(location, "/"), "/")
	if len(parts) >= 2 {
		return prefix + parts[len(parts)-2] + strings.ReplaceAll(parts[len(parts)-1], ".", "")
	}
	if len(parts) == 1 {
		return prefix + strings.ReplaceAll(parts[0], ".", "")
	}
	return prefix + "v1"
}
