// pkg/generate/registry_generator.go
package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/ialexeze/orkestra/pkg/utils"
)

const outputDir = "initialize"

// ── Katalog subset ────────────────────────────────────────────────────────────
// We only unmarshal what the generator needs — not the full Katalog type.
// This keeps the generator self-contained and avoids importing initialize.

type generateKatalog struct {
	Spec struct {
		CRDs []generateCRDEntry `yaml:"crds"`
	} `yaml:"spec"`
}

type generateCRDEntry struct {
	Name    string `yaml:"name"`
	Enabled bool   `yaml:"enabled"`

	APITypes struct {
		Object   string `yaml:"object"`
		List     string `yaml:"list"`
		Alias    string `yaml:"alias"`
		Group    string `yaml:"group"`
		Version  string `yaml:"version"`
		Kind     string `yaml:"kind"`
		Location string `yaml:"location"`
	} `yaml:"apiTypes"`

	Reconciler struct {
		Default bool `yaml:"default"`
	} `yaml:"reconciler"`
}

// ── Template data ─────────────────────────────────────────────────────────────

type registryTemplateData struct {
	Timestamp string
	Imports   []importEntry
	Entries   []registryEntry
}

type importEntry struct {
	Alias    string
	Location string
}

type registryEntry struct {
	Alias   string
	Object  string
	List    string
	Group   string
	Version string
	Kind    string
}

// ── Template ──────────────────────────────────────────────────────────────────

var registryTemplate = template.Must(template.New("registry").Parse(`// initialize/registry.go
// Code generated by "ork generate registry" on {{ .Timestamp }}. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
package initialize

import (
	"fmt"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
{{ range .Imports }}
	{{ .Alias }} "{{ .Location }}"
{{ end }})

// RegisterRuntimeObjects populates ObjectRegistry and ListRegistry for all
// enabled CRDs with reconciler.default: true in the Katalog.
// Called by NewKatalog() in YAML mode before Katalog validation.
func RegisterRuntimeObjects() {
{{ range .Entries }}
	// {{ .Object }}
	ObjectRegistry[schema.GroupVersionKind{
		Group:   "{{ .Group }}",
		Version: "{{ .Version }}",
		Kind:    "{{ .Kind }}",
	}] = func() runtime.Object { return &{{ .Alias }}.{{ .Object }}{} }

	ListRegistry[schema.GroupVersionKind{
		Group:   "{{ .Group }}",
		Version: "{{ .Version }}",
		Kind:    "{{ .Kind }}",
	}] = func() runtime.Object { return &{{ .Alias }}.{{ .List }}{} }
{{ end }}}

// RegisterScheme registers all generated CRD types into the provided scheme.
// Called by NewSchemeRegistry() in YAML mode.
func RegisterScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
{{ range .Entries }}	if err := {{ .Alias }}.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register {{ .Object }} scheme: %w", err)
	}
{{ end }}	return scheme, nil
}
`))

// ── Registry ──────────────────────────────────────────────────────────────────

// Registry reads a Katalog from path (local file or remote URL), validates it,
// and writes initialize/registry.go into outputDir.
// Only enabled CRDs with reconciler.default: true are emitted.
// The output file is created if it does not exist and overwritten on each run.
func Registry(katalogPath string) error {
	// ── 1. Load ───────────────────────────────────────────────────────────────
	data, err := utils.LoadFile(katalogPath)
	if err != nil {
		return fmt.Errorf("loading katalog from %q: %w", katalogPath, err)
	}

	// ── 2. Validate + parse ───────────────────────────────────────────────────
	kat, err := parseKatalog(data)
	if err != nil {
		return err
	}

	if len(kat.Spec.CRDs) == 0 {
		return fmt.Errorf("katalog has no CRDs defined")
	}

	// ── 3. Collect entries for default reconciler CRDs ────────────────────────
	var imports []importEntry
	var entries []registryEntry

	seenAliases := map[string]string{} // alias → location, for dedup

	for _, crd := range kat.Spec.CRDs {
		if !crd.Enabled {
			continue // disabled — skip
		}
		if !crd.Reconciler.Default {
			continue // custom reconciler — user wires this themselves
		}

		// Validate required apiTypes fields
		if err := validateAPITypes(crd); err != nil {
			return fmt.Errorf("CRD %q: %w", crd.Name, err)
		}

		alias := resolveAlias(crd)

		// Dedup imports — multiple CRDs could share a package (unusual but safe)
		if existing, seen := seenAliases[alias]; seen && existing != crd.APITypes.Location {
			return fmt.Errorf("CRD %q: alias %q conflicts with %q — set a unique alias",
				crd.Name, alias, existing)
		}
		if _, seen := seenAliases[alias]; !seen {
			seenAliases[alias] = crd.APITypes.Location
			imports = append(imports, importEntry{
				Alias:    alias,
				Location: crd.APITypes.Location,
			})
		}

		entries = append(entries, registryEntry{
			Alias:   alias,
			Object:  crd.APITypes.Object,
			List:    crd.APITypes.List,
			Group:   crd.APITypes.Group,
			Version: crd.APITypes.Version,
			Kind:    crd.APITypes.Kind,
		})
	}

	if len(entries) == 0 {
		return fmt.Errorf("no enabled CRDs with reconciler.default: true found — nothing to generate")
	}

	// ── 4. Render template ────────────────────────────────────────────────────
	var buf bytes.Buffer
	if err := registryTemplate.Execute(&buf, registryTemplateData{
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Imports:   imports,
		Entries:   entries,
	}); err != nil {
		return fmt.Errorf("rendering template: %w", err)
	}

	// ── 5. Format with gofmt ──────────────────────────────────────────────────
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return the unformatted source in the error so the template bug is visible
		return fmt.Errorf("gofmt failed (template bug):\n%s\n\nerror: %w", buf.String(), err)
	}

	// ── 6. Write ──────────────────────────────────────────────────────────────
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("creating output directory %q: %w", outputDir, err)
	}

	outPath := filepath.Join(outputDir, "registry.go")

	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		return fmt.Errorf("writing %q: %w", outPath, err)
	}

	return nil
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func validateAPITypes(crd generateCRDEntry) error {
	t := crd.APITypes
	var missing []string

	if t.Object == "" {
		missing = append(missing, "apiTypes.object")
	}
	if t.List == "" {
		missing = append(missing, "apiTypes.list")
	}
	if t.Group == "" {
		missing = append(missing, "apiTypes.group")
	}
	if t.Version == "" {
		missing = append(missing, "apiTypes.version")
	}
	if t.Kind == "" {
		missing = append(missing, "apiTypes.kind")
	}
	if t.Location == "" {
		missing = append(missing, "apiTypes.location")
	}

	if len(missing) > 0 {
		return fmt.Errorf("missing required apiTypes fields: %s", strings.Join(missing, ", "))
	}

	return nil
}

// resolveAlias returns the import alias for a CRD entry.
// Uses apiTypes.alias if set, otherwise derives from the last segment of location.
// e.g. "github.com/org/repo/api/types/project/v1alpha1" → "v1alpha1"
// which is then prefixed with the CRD name to avoid collisions:
// "project" + "v1alpha1" → "projectv1alpha1"
// If alias is explicitly set, it is used as-is.
func resolveAlias(crd generateCRDEntry) string {
	if crd.APITypes.Alias != "" {
		return crd.APITypes.Alias
	}

	// Derive from last two segments of location path to avoid single-segment collisions
	// e.g. ".../project/v1alpha1" → "projectv1alpha1"
	parts := strings.Split(strings.TrimRight(crd.APITypes.Location, "/"), "/")
	if len(parts) >= 2 {
		return parts[len(parts)-2] + strings.ReplaceAll(parts[len(parts)-1], ".", "")
	}
	if len(parts) == 1 {
		return parts[0]
	}

	// Fallback to CRD name — should not reach here with a valid location
	return strings.ToLower(crd.Name) + "v1"
}
