// pkg/generate/registry_generator.go
package generate

import (
	"fmt"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	orktypes "github.com/ialexeze/orkestra/pkg/types"
	"github.com/ialexeze/orkestra/pkg/utils"
)

var registryTemplate = template.Must(template.New("registry").Parse(`// pkg/runtime/generated_runtime_registry.go
// Code generated by "ork generate registry" on {{ .Timestamp }}. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
package runtime

import (
	"fmt"

	orktypes "github.com/ialexeze/orkestra/pkg/types"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	{{ if or .NeedsHookImports .NeedsRecImports }}
	"github.com/ialexeze/orkestra/domain"
	 {{ end }}{{ if .NeedsRecImports }}
	"github.com/ialexeze/orkestra/pkg/kubeclient"
	"github.com/ialexeze/orkestra/pkg/event"
	"k8s.io/client-go/tools/cache"
{{ end }}
{{ range .Imports }}	{{ .Alias }} "{{ .Location }}"
{{ end }})

func RegisterRuntimeObjects() {
{{ range .Entries }}
	orktypes.ObjectRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() runtime.Object { return &{{ .Alias }}.{{ .Object }}{} }
	orktypes.ListRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() runtime.Object { return &{{ .Alias }}.{{ .List }}{} }
{{ end }}{{ if .HookEntries }}
	{{ range .HookEntries }}
	orktypes.HookRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() domain.AnyReconcileHooks {
			return {{ .Alias }}.{{ .Function }}()
		}
{{ end }}{{ end }}{{ if .RecEntries }}
{{ range .RecEntries }}
	orktypes.ReconcilerRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func(kube *kubeclient.Kubeclient, inf cache.SharedIndexInformer, ev *event.Event) domain.Reconciler {
			return {{ .Alias }}.{{ .Function }}(kube, inf, ev)
		}
{{ end }}{{ end }}}

func RegisterScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
{{ range .Entries }}	if err := {{ .Alias }}.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register {{ .Object }} scheme: %w", err)
	}
{{ end }}	return scheme, nil
}
`))

func Runtime(katalogPath string, dryRun bool) error {

	// ── 1. Load ───────────────────────────────────────────────────────────────
	data, err := utils.LoadFile(katalogPath)
	if err != nil {
		return fmt.Errorf("loading katalog from %q: %w", katalogPath, err)
	}

	// ── 2. Parse ──────────────────────────────────────────────────────────────
	kat, err := parseKatalog(data)
	if err != nil {
		return err
	}

	var (
		imports     []importEntry
		entries     []registryEntry   // typed CRDs → ObjectRegistry + ListRegistry + RegisterScheme
		hookEntries []hookEntry       // Go hooks → HookRegistry
		recEntries  []reconcilerEntry // custom reconcilers → ReconcilerRegistry

		seenObjectAliases = map[string]string{}
		seenHookAliases   = map[string]string{}
		seenRecAliases    = map[string]string{}
	)

	for _, crd := range kat.Spec.CRDs {
		if !crd.Enabled {
			continue
		}

		// ── Typed CRDs — object registry + scheme ────────────────────────────
		// Dynamic CRDs skip this block entirely — they use the dynamic
		// client and *unstructured.Unstructured, no scheme registration needed.
		if !crd.IsDynamic() && crd.APITypes.Location != "" {

			if err := validateAPITypes(crd); err != nil {
				return fmt.Errorf("CRD %q: %w", crd.Name, err)
			}

			alias := resolveAlias(crd.APITypes.Alias, crd.Name, crd.APITypes.Location)

			if err := dedupeImport(seenObjectAliases, alias, crd.APITypes.Location, crd.Name); err != nil {
				return err
			}
			if _, seen := seenObjectAliases[alias]; !seen {
				imports = append(imports, importEntry{Alias: alias, Location: crd.APITypes.Location})
				seenObjectAliases[alias] = crd.APITypes.Location
			}

			// entries drives both ObjectRegistry/ListRegistry AND RegisterScheme
			entries = append(entries, registryEntry{
				Alias:   alias,
				Object:  crd.APITypes.Object,
				List:    crd.APITypes.List,
				Group:   crd.APITypes.Group,
				Version: crd.APITypes.Version,
				Kind:    crd.APITypes.Kind,
			})
		}

		// ── Go hooks — HookRegistry ───────────────────────────────────────────
		// Only for default: true CRDs with an explicit hooks declaration.
		// Dynamic CRDs with OnCreate/OnReconcile/OnDelete templates are
		// handled by Hooks() below — they do not go through HookRegistry here.
		if crd.ReconcilerConfig.Default && crd.ReconcilerConfig.Hooks != nil {
			h := crd.ReconcilerConfig.Hooks

			if err := validateHookEntry(h, crd.Name); err != nil {
				return err
			}

			hookAlias := resolveAlias(h.Alias, crd.Name+"hooks", h.Location)

			if err := dedupeImport(seenHookAliases, hookAlias, h.Location, crd.Name); err != nil {
				return err
			}
			if _, seen := seenHookAliases[hookAlias]; !seen {
				imports = append(imports, importEntry{Alias: hookAlias, Location: h.Location})
				seenHookAliases[hookAlias] = h.Location
			}

			hookEntries = append(hookEntries, hookEntry{
				Alias:    hookAlias,
				Function: h.Function,
				Group:    crd.APITypes.Group,
				Version:  crd.APITypes.Version,
				Kind:     crd.APITypes.Kind,
			})
		}

		// ── Custom reconcilers — ReconcilerRegistry ───────────────────────────
		if !crd.ReconcilerConfig.Default {
			if crd.ReconcilerConfig.ConstructorDecl == nil {
				return fmt.Errorf(
					"CRD %q: reconciler.default is false but no constructor declared — "+
						"add reconciler.constructor with location and function, "+
						"then re-run ork generate registry",
					crd.Name,
				)
			}

			c := crd.ReconcilerConfig.ConstructorDecl

			if err := validateConstructorEntry(c, crd.Name); err != nil {
				return err
			}

			recAlias := resolveAlias(c.Alias, crd.Name+"rec", c.Location)

			if err := dedupeImport(seenRecAliases, recAlias, c.Location, crd.Name); err != nil {
				return err
			}
			if _, seen := seenRecAliases[recAlias]; !seen {
				imports = append(imports, importEntry{Alias: recAlias, Location: c.Location})
				seenRecAliases[recAlias] = c.Location
			}

			recEntries = append(recEntries, reconcilerEntry{
				Alias:    recAlias,
				Function: c.Function,
				Group:    crd.APITypes.Group,
				Version:  crd.APITypes.Version,
				Kind:     crd.APITypes.Kind,
			})
		}
	}

	// ── Guard — nothing to generate ───────────────────────────────────────────
	// Fail only if there are truly no entries of any kind AND no template CRDs.
	// Pure dynamic template-only Katalogs are valid — Hooks() handles them.
	if len(entries) == 0 && len(recEntries) == 0 && len(hookEntries) == 0 {
		hasTemplates := false
		for _, crd := range kat.Spec.CRDs {
			if crd.Enabled && crd.HasTemplates() {
				hasTemplates = true
				break
			}
		}
		if !hasTemplates {
			return fmt.Errorf(
				"no enabled CRDs found — " +
					"check that at least one CRD has enabled: true",
			)
		}
	}

	// ── Render registry file ──────────────────────────────────────────────────
	// Only write the file if there is typed/hook/constructor content.
	// Pure template Katalogs skip this — __generated_runtime_registry.go
	// stays as the committed stub with empty RegisterRuntimeObjects().
	if len(entries) > 0 || len(recEntries) > 0 || len(hookEntries) > 0 {
		registryData := registryTemplateData{
			Timestamp:        time.Now().UTC().Format(time.RFC3339),
			Imports:          imports,
			Entries:          entries, // used by ObjectRegistry, ListRegistry, RegisterScheme
			HookEntries:      hookEntries,
			RecEntries:       recEntries,
			NeedsRecImports:  len(recEntries) > 0,
			NeedsHookImports: len(hookEntries) > 0,
		}

		outPath := filepath.Join(RuntimePackage, RegistryFile)
		if err := renderTemplateToFile(registryTemplate, registryData, outPath, true, dryRun); err != nil {
			return err
		}
	}

	// ── Emit hooks file for declarative template CRDs ─────────────────────────
	// Hooks() is always called — it skips silently if no CRDs have templates.
	if err := Hooks(katalogPath, dryRun); err != nil {
		return fmt.Errorf("generating hooks: %w", err)
	}

	return nil
}

func validateAPITypes(crd orktypes.CRDEntry) error {
	t := crd.APITypes
	var missing []string
	if t.Object == "" {
		missing = append(missing, "apiTypes.object")
	}
	if t.List == "" {
		missing = append(missing, "apiTypes.list")
	}
	if t.Group == "" {
		missing = append(missing, "apiTypes.group")
	}
	if t.Version == "" {
		missing = append(missing, "apiTypes.version")
	}
	if t.Kind == "" {
		missing = append(missing, "apiTypes.kind")
	}
	if t.Location == "" {
		missing = append(missing, "apiTypes.location")
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required apiTypes fields: %s", strings.Join(missing, ", "))
	}
	return nil
}

func validateHookEntry(h *orktypes.HookDeclaration, crdName string) error {
	var missing []string
	if h.Location == "" {
		missing = append(missing, "reconciler.hooks.location")
	}
	if h.Function == "" {
		missing = append(missing, "reconciler.hooks.function")
	}
	if len(missing) > 0 {
		return fmt.Errorf("CRD %q: missing required hook fields: %s", crdName, strings.Join(missing, ", "))
	}
	return nil
}

func validateConstructorEntry(c *orktypes.ConstructorDeclaration, crdName string) error {
	var missing []string
	if c.Location == "" {
		missing = append(missing, "reconciler.constructor.location")
	}
	if c.Function == "" {
		missing = append(missing, "reconciler.constructor.function")
	}
	if len(missing) > 0 {
		return fmt.Errorf("CRD %q: missing required constructor fields: %s", crdName, strings.Join(missing, ", "))
	}
	return nil
}

func dedupeImport(seen map[string]string, alias, location, crdName string) error {
	if existing, ok := seen[alias]; ok && existing != location {
		return fmt.Errorf(
			"CRD %q: import alias %q is already used for %q — set a unique alias in the Katalog entry",
			crdName, alias, existing,
		)
	}
	return nil
}

func resolveAlias(explicitAlias, prefix, location string) string {
	if explicitAlias != "" {
		return explicitAlias
	}
	parts := strings.Split(strings.TrimRight(location, "/"), "/")
	if len(parts) >= 2 {
		return prefix + parts[len(parts)-2] + strings.ReplaceAll(parts[len(parts)-1], ".", "")
	}
	if len(parts) == 1 {
		return prefix + strings.ReplaceAll(parts[0], ".", "")
	}
	return prefix + "v1"
}
