{{- if and .Values.runtime.enabled (not .Values.runtime.katalog.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orkestra.fullname" . }}-katalog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orkestra.labels" . | nindent 4 }}
    component: runtime
data:
  {{ .Values.runtime.katalog.configMapKey }}: |
    {{- .Values.runtime.katalog.inline | nindent 4 }}
{{- end }}