{{- if and .Values.controlCenter.enabled .Values.controlCenter.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orkestra.ccServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orkestra.labels" . | nindent 4 }}
    component: controlcenter
  {{- with .Values.controlCenter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false

{{- end }}