# Runtime PodDisruptionBudget
{{- if .Values.runtime.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "orkestra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orkestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
spec:
  selector:
    matchLabels:
      {{- include "orkestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: runtime
  {{- if .Values.runtime.pdb.minAvailable }}
  minAvailable: {{ .Values.runtime.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.runtime.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.runtime.pdb.maxUnavailable }}
  {{- end }}
{{- end }}

# Control Center PodDisruptionBudget
{{- if and .Values.controlCenter.pdb.enabled .Values.controlCenter.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "orkestra.fullname" . }}-cc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orkestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: controlcenter
spec:
  selector:
    matchLabels:
      {{- include "orkestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controlcenter
  {{- if .Values.controlCenter.pdb.minAvailable }}
  minAvailable: {{ .Values.controlCenter.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.controlCenter.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.controlCenter.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
