apiVersion: v1
kind: Service
metadata:
  name: {{ include "orkestra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orkestra.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "orkestra.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
