apiVersion: demo.orkestra.io/v1
kind: JobQueue
metadata:
  name: my-queue
  namespace: default
spec:
  image: nginx:1.25
  port: 8080
  initialDepth: 150
---
apiVersion: demo.orkestra.io/v1
kind: JobWorker
metadata:
  name: my-worker
  namespace: default
spec:
  image: nginx:1.25
  port: 9090
  queueName: my-queue
