apiVersion: orkestra.orkspace.io/v1
kind: Katalog
metadata:
  name: platform-security

gateway:
  standalone: true


security:
  deletionProtection:
    enabled: true
    strictMode: true
    cleanupOnShutdown: true

spec:
  crds:
    platform:
      apiTypes:
        kind: Namespace
      operatorBox:
        onCreate:
          namespaces:
            - name: "{{ .metadata.name }}"
              labels:
                - key: orkestra.io/deletion-protection
                  value: "true"
              reconcile: true