# Website
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.demo.orkestra.io
spec:
  group: demo.orkestra.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [image]
              properties:
                image:
                  type: string
                  description: Container image to run
  names:
    kind: Website
    plural: websites
    singular: website
  scope: Namespaced

---
# Postgres from OCI
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgreses.postgres.orkestra.io
spec:
  group: postgres.orkestra.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                  default: "14"
                database:
                  type: string
                user:
                  type: string
  names:
    kind: Postgres
    plural: postgreses
    singular: postgres
  scope: Namespaced

---
# Helm Based Source
# Cache CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: caches.demo.orkestra.io
spec:
  group: demo.orkestra.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [backend]
              properties:
                backend:
                  type: string
                  description: Cache backend type (e.g., redis, memcached)
                size:
                  type: string
                  description: Optional size or tier identifier
  names:
    kind: Cache
    plural: caches
    singular: cache
  scope: Namespaced

# Helm Based Source
# Database CRD
# 
# Uncomment if you want to enable the Database CRD
# 
# ---
# apiVersion: apiextensions.k8s.io/v1
# kind: CustomResourceDefinition
# metadata:
#   name: databases.demo.orkestra.io
# spec:
#   group: demo.orkestra.io
#   versions:
#     - name: v1alpha1
#       served: true
#       storage: true
#       schema:
#         openAPIV3Schema:
#           type: object
#           properties:
#             spec:
#               type: object
#               required: [engine]
#               properties:
#                 engine:
#                   type: string
#                   description: Database engine type (e.g., postgres, mysql)
#                 version:
#                   type: string
#                   description: Optional engine version
#   names:
#     kind: Database
#     plural: databases
#     singular: database
#   scope: Cluster

