apiVersion: orkestra.orkspace.io/v1
kind: E2E
metadata:
  name: workload-autoscaler-suite
  description: >
    Suite for the workload autoscaler track.

imports:
  - ./01-time-based/e2e.yaml
  - ./02-external-api/e2e.yaml
  - ./03-cross-operator/e2e.yaml
