apiVersion: orkestra.orkspace.io/v1
kind: Simulate
metadata:
  name: workload-autoscaler-suite-sim
  description: >
    Workload autoscaler suite. No cluster required.

imports:
  - ./01-time-based/simulate.yaml
  - ./02-external-api/simulate.yaml
  - ./03-cross-operator/simulate.yaml
