apiVersion: rkguide.demo/v1
kind: WebApp
metadata:
  name: my-webapp
  namespace: default
spec:
  image: ghcr.io/orkspace/orkestra-dev-server:0.7.5
  port: 9999
  replicas: 2
  host: ""
  resourceProfile: small