# API CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apis.multi-tenancy.orkestra.io
spec:
  group: multi-tenancy.orkestra.io
  scope: Namespaced
  names:
    plural: apis
    singular: api
    kind: Api
    shortNames:
      - api

  versions:
    - name: v1alpha1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
                cacheName:
                  type: string
                queueName:
                  type: string
              required:
                - image
                - cacheName
                - queueName

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                phase:
                  type: string

      subresources:
        status: {}
---
# Cache CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: caches.multi-tenancy.orkestra.io
spec:
  group: multi-tenancy.orkestra.io
  scope: Namespaced
  names:
    plural: caches
    singular: cache
    kind: Cache
    shortNames:
      - cache

  versions:
    - name: v1alpha1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  default: redis:7-alpine
                replicas:
                  type: integer
                  default: 1


            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                phase:
                  type: string
                endpoint:
                  type: string

      subresources:
        status: {}

---
# Queue CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.multi-tenancy.orkestra.io
spec:
  group: multi-tenancy.orkestra.io
  scope: Namespaced
  names:
    plural: queues
    singular: queue
    kind: Queue
    shortNames:
      - queue

  versions:
    - name: v1alpha1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  default: rabbitmq:3-alpine
                replicas:
                  type: integer
                  default: 1

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                phase:
                  type: string
                amqpEndpoint:
                  type: string

      subresources:
        status: {}
