apiVersion: provisioner.orkestra.io/v1
kind: NamespaceClaim
metadata:
  name: team-delta-claim
spec:
  targetNamespace: team-delta
  team: delta
  owner: delta-operator
  ownerNamespace: default
  tier: medium
