apiVersion: v1
kind: ServiceAccount
metadata:
  name: orkestra
  namespace: ops-team-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orkestra
rules:
- apiGroups: ["platform.orkestra.io"]
  resources: ["projects", "managednamespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["platform.orkestra.io"]
  resources: ["projects/status", "managednamespaces/status"]
  verbs: ["get", "update", "patch"]

- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]

- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orkestra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orkestra
subjects:
- kind: ServiceAccount
  name: orkestra
  namespace: ops-team-ns
