apiVersion: v1
kind: Service
metadata:
  name: multi-crd-controller
  namespace: ops-team-ns
spec:
  selector:
    app: multi-crd-controller
  ports:
  - port: 5000
    targetPort: 5000
    name: health
