// pkg/runtime/generated_runtime_hooks.go
// Code generated by "ork generate registry" on 2026-03-18T01:32:03Z. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
package runtime

import (
	"context"
	"fmt"
	"strconv"

	"github.com/ialexeze/orkestra/domain"
	"github.com/ialexeze/orkestra/pkg/kubeclient"
	orkdeploy "github.com/ialexeze/orkestra/pkg/orkestra-registry/deployments"
	orksvc "github.com/ialexeze/orkestra/pkg/orkestra-registry/services"
	orktmpl "github.com/ialexeze/orkestra/pkg/orkestra-registry/template"
	orktypes "github.com/ialexeze/orkestra/pkg/types"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

func init() {
	registerTemplateHooksWebsite()
	registerTemplateHooksOrkapp()
}

func registerTemplateHooksWebsite() {
	orktypes.HookRegistry[schema.GroupVersionKind{
		Group:   "demo.orkestra.io",
		Version: "v1alpha1",
		Kind:    "Website",
	}] = func() domain.AnyReconcileHooks {
		return domain.ReconcileHooks[domain.Object]{
			OnReconcile: WebsiteOnReconcile,
			OnDelete:    WebsiteOnDelete,
		}
	}
}

func WebsiteOnReconcile(ctx context.Context, obj domain.Object) error {
	kube, ok := kubeclient.FromContext(ctx)
	if !ok || kube == nil {
		return fmt.Errorf("website: kubeclient not found in context")
	}

	resolver, err := orktmpl.NewResolver(ctx, obj)
	if err != nil {
		return fmt.Errorf("website: resolver: %w", err)
	}
	_ = resolver

	// Deployment[0]: onCreate — idempotent create
	{
		resolved, err := resolver.ResolveDeploymentTemplate(orktypes.DeploymentTemplateSource{
			Name:        "{{ .metadata.name }}",
			Image:       "{{ .spec.image }}",
			Replicas:    "{{ .spec.replicas }}",
			Port:        "{{ .spec.port }}",
			Namespace:   "{{ .metadata.namespace }}",
			Labels:      []orktypes.ResourceLabel{{Key: "app", Value: "{{ .metadata.name }}"}, {Key: "managed-by", Value: "orkestra"}, {Key: "crd", Value: "website"}},
			Annotations: []orktypes.ResourceLabel{},
			Resources:   nil,
		})
		if err != nil {
			return fmt.Errorf("website: deployment[0]: %w", err)
		}
		staticReplicas, _ := strconv.Atoi("1")
		spec := orkdeploy.Resolve(resolved, staticReplicas, resolver.OwnerName())
		if err := orkdeploy.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("website: deployment[0].create: %w", err)
		}
	}

	// Deployment[0]: onReconcile — drift correction
	{
		resolved, err := resolver.ResolveDeploymentTemplate(orktypes.DeploymentTemplateSource{
			Name:        "{{ .metadata.name }}",
			Image:       "{{ .spec.image }}",
			Replicas:    "{{ .spec.replicas }}",
			Port:        "{{ .spec.port }}",
			Namespace:   "{{ .metadata.namespace }}",
			Labels:      []orktypes.ResourceLabel{{Key: "app", Value: "{{ .metadata.name }}"}, {Key: "managed-by", Value: "orkestra"}, {Key: "crd", Value: "website"}},
			Annotations: []orktypes.ResourceLabel{},
			Resources:   nil,
		})
		if err != nil {
			return fmt.Errorf("website: onReconcile deployment[0]: %w", err)
		}
		staticReplicas, _ := strconv.Atoi("1")
		spec := orkdeploy.Resolve(resolved, staticReplicas, resolver.OwnerName())
		if err := orkdeploy.Update(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("website: onReconcile deployment[0].update: %w", err)
		}
	}

	// Service[0]: onCreate
	{
		resolved, err := resolver.ResolveServiceTemplate(orktypes.ServiceTemplateSource{
			Name:       "{{ .metadata.name }}-svc",
			Type:       "{{ .spec.serviceType }}",
			Port:       "80",
			TargetPort: "{{ .spec.port }}",
			Namespace:  "{{ .metadata.namespace }}",
			Labels:     []orktypes.ResourceLabel{{Key: "app", Value: "{{ .metadata.name }}"}, {Key: "managed-by", Value: "orkestra"}},
		})
		if err != nil {
			return fmt.Errorf("website: service[0]: %w", err)
		}
		spec := orksvc.Resolve(resolved, resolver.OwnerName())
		if err := orksvc.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("website: service[0].create: %w", err)
		}
	}

	// Service[0]: onReconcile
	{
		resolved, err := resolver.ResolveServiceTemplate(orktypes.ServiceTemplateSource{
			Name:       "{{ .metadata.name }}-svc",
			Type:       "{{ .spec.serviceType }}",
			Port:       "80",
			TargetPort: "{{ .spec.port }}",
			Namespace:  "{{ .metadata.namespace }}",
			Labels:     []orktypes.ResourceLabel{{Key: "app", Value: "{{ .metadata.name }}"}, {Key: "managed-by", Value: "orkestra"}},
		})
		if err != nil {
			return fmt.Errorf("website: onReconcile service[0]: %w", err)
		}
		spec := orksvc.Resolve(resolved, resolver.OwnerName())
		if err := orksvc.Update(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("website: onReconcile service[0].update: %w", err)
		}
	}

	return nil
}

func WebsiteOnDelete(ctx context.Context, obj domain.Object) error {
	// No explicit onDelete templates — owner references handle cleanup automatically.
	return nil
}

func registerTemplateHooksOrkapp() {
	orktypes.HookRegistry[schema.GroupVersionKind{
		Group:   "orkestra.konduktor.io",
		Version: "v1alpha1",
		Kind:    "OrkApp",
	}] = func() domain.AnyReconcileHooks {
		return domain.ReconcileHooks[domain.Object]{
			OnReconcile: OrkappOnReconcile,
			OnDelete:    OrkappOnDelete,
		}
	}
}

func OrkappOnReconcile(ctx context.Context, obj domain.Object) error {
	kube, ok := kubeclient.FromContext(ctx)
	if !ok || kube == nil {
		return fmt.Errorf("orkapp: kubeclient not found in context")
	}

	resolver, err := orktmpl.NewResolver(ctx, obj)
	if err != nil {
		return fmt.Errorf("orkapp: resolver: %w", err)
	}
	_ = resolver

	// Deployment[0]: onCreate — idempotent create
	{
		resolved, err := resolver.ResolveDeploymentTemplate(orktypes.DeploymentTemplateSource{
			Name:        "{{ .metadata.name }}-app",
			Image:       "{{ .spec.image }}",
			Replicas:    "{{ .spec.replicas }}",
			Port:        "8080",
			Namespace:   "{{ .metadata.namespace }}",
			Labels:      []orktypes.ResourceLabel{{Key: "app", Value: "{{ .metadata.name }}"}, {Key: "managed-by", Value: "orkestra"}},
			Annotations: []orktypes.ResourceLabel{},
			Resources:   &orktypes.ResourceRequirements{Requests: map[string]string{"cpu": "100m", "memory": "128Mi"}, Limits: map[string]string{"cpu": "500m", "memory": "512Mi"}},
		})
		if err != nil {
			return fmt.Errorf("orkapp: deployment[0]: %w", err)
		}
		staticReplicas, _ := strconv.Atoi("1")
		spec := orkdeploy.Resolve(resolved, staticReplicas, resolver.OwnerName())
		if err := orkdeploy.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("orkapp: deployment[0].create: %w", err)
		}
	}

	// Deployment[0]: onReconcile — drift correction
	{
		resolved, err := resolver.ResolveDeploymentTemplate(orktypes.DeploymentTemplateSource{
			Name:        "{{ .metadata.name }}-app",
			Image:       "{{ .spec.image }}",
			Replicas:    "{{ .spec.replicas }}",
			Port:        "",
			Namespace:   "",
			Labels:      []orktypes.ResourceLabel{},
			Annotations: []orktypes.ResourceLabel{},
			Resources:   nil,
		})
		if err != nil {
			return fmt.Errorf("orkapp: onReconcile deployment[0]: %w", err)
		}
		staticReplicas, _ := strconv.Atoi("1")
		spec := orkdeploy.Resolve(resolved, staticReplicas, resolver.OwnerName())
		if err := orkdeploy.Update(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("orkapp: onReconcile deployment[0].update: %w", err)
		}
	}

	// Service[0]: onCreate
	{
		resolved, err := resolver.ResolveServiceTemplate(orktypes.ServiceTemplateSource{
			Name:       "{{ .metadata.name }}-svc",
			Type:       "ClusterIP",
			Port:       "80",
			TargetPort: "8080",
			Namespace:  "{{ .metadata.namespace }}",
			Labels:     []orktypes.ResourceLabel{{Key: "app", Value: "{{ .metadata.name }}"}},
		})
		if err != nil {
			return fmt.Errorf("orkapp: service[0]: %w", err)
		}
		spec := orksvc.Resolve(resolved, resolver.OwnerName())
		if err := orksvc.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("orkapp: service[0].create: %w", err)
		}
	}

	return nil
}

func OrkappOnDelete(ctx context.Context, obj domain.Object) error {
	// No explicit onDelete templates — owner references handle cleanup automatically.
	return nil
}
