// pkg/runtime/generated_runtime_registry.go
// Code generated by "ork generate registry" on 2026-03-15T09:52:59Z. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
package runtime

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func RegisterRuntimeObjects() {}

func RegisterScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
	return scheme, nil
}
