// pkg/runtime/generated_runtime_hooks.go
// Code generated by "ork generate runtime" on 2026-03-18T10:00:09Z. DO NOT EDIT.
// Re-generate by running: ork generate runtime --katalog <path-or-url>
package runtime

import (
	"context"
	"fmt"
	"github.com/ialexeze/orkestra/domain"
	"github.com/ialexeze/orkestra/pkg/kubeclient"
	orkcm "github.com/ialexeze/orkestra/pkg/orkestra-registry/configmaps"
	orksecrets "github.com/ialexeze/orkestra/pkg/orkestra-registry/secrets"
	orktmpl "github.com/ialexeze/orkestra/pkg/orkestra-registry/template"
	orktypes "github.com/ialexeze/orkestra/pkg/types"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

func init() {
	registerTemplateHooksPlatformnamespace()
}

func registerTemplateHooksPlatformnamespace() {
	orktypes.HookRegistry[schema.GroupVersionKind{
		Group:   "platform.example.io",
		Version: "v1alpha1",
		Kind:    "PlatformNamespace",
	}] = func() domain.AnyReconcileHooks {
		return domain.ReconcileHooks[domain.Object]{
			OnReconcile: PlatformnamespaceOnReconcile,
			OnDelete:    PlatformnamespaceOnDelete,
		}
	}
}

func PlatformnamespaceOnReconcile(ctx context.Context, obj domain.Object) error {
	kube, ok := kubeclient.FromContext(ctx)
	if !ok || kube == nil {
		return fmt.Errorf("platformnamespace: kubeclient not found in context")
	}

	resolver, err := orktmpl.NewResolver(ctx, obj)
	if err != nil {
		return fmt.Errorf("platformnamespace: resolver: %w", err)
	}
	_ = resolver

	// Secret[0]: onCreate
	{
		resolved, err := resolver.ResolveSecretTemplate(orktypes.SecretTemplateSource{
			Name:          "db-credentials",
			Namespace:     "{{ .spec.targetNamespace }}",
			Type:          "",
			FromSecret:    "master-db-credentials",
			FromNamespace: "platform",
			Data:          map[string]string{},
			ToNamespaces:  []string{},
		})
		if err != nil {
			return fmt.Errorf("platformnamespace: secret[0]: %w", err)
		}
		spec := orksecrets.Resolve(resolved, resolver.OwnerName())
		if err := orksecrets.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("platformnamespace: secret[0].create: %w", err)
		}
	}

	// Secret[1]: onCreate
	{
		resolved, err := resolver.ResolveSecretTemplate(orktypes.SecretTemplateSource{
			Name:          "registry-pull-secret",
			Namespace:     "{{ .spec.targetNamespace }}",
			Type:          "",
			FromSecret:    "docker-registry-creds",
			FromNamespace: "platform",
			Data:          map[string]string{},
			ToNamespaces:  []string{"{{ .spec.targetNamespace }}"},
		})
		if err != nil {
			return fmt.Errorf("platformnamespace: secret[1]: %w", err)
		}
		spec := orksecrets.Resolve(resolved, resolver.OwnerName())
		if err := orksecrets.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("platformnamespace: secret[1].create: %w", err)
		}
	}

	// Secret[2]: onCreate
	{
		resolved, err := resolver.ResolveSecretTemplate(orktypes.SecretTemplateSource{
			Name:          "{{ .metadata.name }}-app-secret",
			Namespace:     "{{ .spec.targetNamespace }}",
			Type:          "",
			FromSecret:    "",
			FromNamespace: "",
			Data:          map[string]string{"ENVIRONMENT": "{{ .spec.environment }}", "REGION": "{{ .spec.region }}"},
			ToNamespaces:  []string{},
		})
		if err != nil {
			return fmt.Errorf("platformnamespace: secret[2]: %w", err)
		}
		spec := orksecrets.Resolve(resolved, resolver.OwnerName())
		if err := orksecrets.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("platformnamespace: secret[2].create: %w", err)
		}
	}

	// Secret[0]: onReconcile
	{
		resolved, err := resolver.ResolveSecretTemplate(orktypes.SecretTemplateSource{
			Name:          "db-credentials",
			Namespace:     "{{ .spec.targetNamespace }}",
			Type:          "",
			FromSecret:    "master-db-credentials",
			FromNamespace: "platform",
			Data:          map[string]string{},
			ToNamespaces:  []string{},
		})
		if err != nil {
			return fmt.Errorf("platformnamespace: secret[0]: %w", err)
		}
		spec := orksecrets.Resolve(resolved, resolver.OwnerName())
		if err := orksecrets.Update(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("platformnamespace: secret[0].update: %w", err)
		}
	}

	// ConfigMap[0]: onCreate
	{
		resolved, err := resolver.ResolveConfigMapTemplate(orktypes.ConfigMapTemplateSource{
			Name:          "app-config",
			Namespace:     "{{ .spec.targetNamespace }}",
			FromConfigMap: "base-app-config",
			FromNamespace: "platform",
			Data:          map[string]string{"LOG_LEVEL": "{{ .spec.logLevel }}", "NAMESPACE": "{{ .spec.targetNamespace }}"},
			ToNamespaces:  []string{},
		})
		if err != nil {
			return fmt.Errorf("platformnamespace: configmap[0]: %w", err)
		}
		spec := orkcm.Resolve(resolved, resolver.OwnerName())
		if err := orkcm.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("platformnamespace: configmap[0].create: %w", err)
		}
	}

	// ConfigMap[1]: onCreate
	{
		resolved, err := resolver.ResolveConfigMapTemplate(orktypes.ConfigMapTemplateSource{
			Name:          "monitoring-config",
			Namespace:     "",
			FromConfigMap: "prometheus-scrape-config",
			FromNamespace: "monitoring",
			Data:          map[string]string{},
			ToNamespaces:  []string{"{{ .spec.targetNamespace }}"},
		})
		if err != nil {
			return fmt.Errorf("platformnamespace: configmap[1]: %w", err)
		}
		spec := orkcm.Resolve(resolved, resolver.OwnerName())
		if err := orkcm.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("platformnamespace: configmap[1].create: %w", err)
		}
	}

	// ConfigMap[2]: onCreate
	{
		resolved, err := resolver.ResolveConfigMapTemplate(orktypes.ConfigMapTemplateSource{
			Name:          "{{ .metadata.name }}-feature-flags",
			Namespace:     "{{ .spec.targetNamespace }}",
			FromConfigMap: "",
			FromNamespace: "",
			Data:          map[string]string{"FEATURE_BETA_API": "false", "FEATURE_NEW_UI": "false", "MAX_CONNECTIONS": "100"},
			ToNamespaces:  []string{},
		})
		if err != nil {
			return fmt.Errorf("platformnamespace: configmap[2]: %w", err)
		}
		spec := orkcm.Resolve(resolved, resolver.OwnerName())
		if err := orkcm.Create(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("platformnamespace: configmap[2].create: %w", err)
		}
	}

	// ConfigMap[0]: onReconcile
	{
		resolved, err := resolver.ResolveConfigMapTemplate(orktypes.ConfigMapTemplateSource{
			Name:          "app-config",
			Namespace:     "{{ .spec.targetNamespace }}",
			FromConfigMap: "base-app-config",
			FromNamespace: "platform",
			Data:          map[string]string{"LOG_LEVEL": "{{ .spec.logLevel }}", "NAMESPACE": "{{ .spec.targetNamespace }}"},
			ToNamespaces:  []string{},
		})
		if err != nil {
			return fmt.Errorf("platformnamespace: configmap[0]: %w", err)
		}
		spec := orkcm.Resolve(resolved, resolver.OwnerName())
		if err := orkcm.Update(ctx, kube, obj, spec); err != nil {
			return fmt.Errorf("platformnamespace: configmap[0].update: %w", err)
		}
	}

	return nil
}

func PlatformnamespaceOnDelete(ctx context.Context, obj domain.Object) error {
	// No explicit onDelete templates — owner references handle cleanup automatically.
	return nil
}
