// pkg/runtime/generated_runtime_registry.go
// Code generated by "ork generate registry" on 2026-03-15T06:44:37Z. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
package runtime

import (
	"fmt"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	"github.com/ialexeze/orkestra/domain"

	"github.com/ialexeze/orkestra/pkg/event"
	"github.com/ialexeze/orkestra/pkg/kubeclient"
	"k8s.io/client-go/tools/cache"

	mnsv1 "github.com/ialexeze/orkestra/example-crds/api/types/managedNamespace/v1alpha1"
	projv1 "github.com/ialexeze/orkestra/example-crds/api/types/project/v1alpha1"
	mnsreconciler "github.com/ialexeze/orkestra/pkg/reconciler"
	projecthooks "github.com/ialexeze/orkestra/pkg/reconciler/hooks"
)

func RegisterRuntimeObjects() {

	ObjectRegistry[schema.GroupVersionKind{Group: "platform.orkestra.io", Version: "v1alpha1", Kind: "Project"}] =
		func() runtime.Object { return &projv1.Project{} }
	ListRegistry[schema.GroupVersionKind{Group: "platform.orkestra.io", Version: "v1alpha1", Kind: "Project"}] =
		func() runtime.Object { return &projv1.ProjectList{} }

	ObjectRegistry[schema.GroupVersionKind{Group: "platform.orkestra.io", Version: "v1alpha1", Kind: "ManagedNamespace"}] =
		func() runtime.Object { return &mnsv1.ManagedNamespace{} }
	ListRegistry[schema.GroupVersionKind{Group: "platform.orkestra.io", Version: "v1alpha1", Kind: "ManagedNamespace"}] =
		func() runtime.Object { return &mnsv1.ManagedNamespaceList{} }

	HookRegistry[schema.GroupVersionKind{Group: "platform.orkestra.io", Version: "v1alpha1", Kind: "Project"}] =
		func() domain.AnyReconcileHooks {
			return projecthooks.ProjectHooks()
		}

	ReconcilerRegistry[schema.GroupVersionKind{Group: "platform.orkestra.io", Version: "v1alpha1", Kind: "ManagedNamespace"}] =
		func(kube *kubeclient.Kubeclient, inf cache.SharedIndexInformer, ev *event.Event) domain.Reconciler {
			return mnsreconciler.NewManagedNamespaceReconciler(kube, inf, ev)
		}
}

func RegisterScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
	if err := projv1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register Project scheme: %w", err)
	}
	if err := mnsv1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register ManagedNamespace scheme: %w", err)
	}
	return scheme, nil
}
