// pkg/runtime/types.go
package runtime

import (
	"time"

	"github.com/ialexeze/orkestra/domain"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// ── Registries ────────────────────────────────────────────────────────────────
// Populated by RegisterRuntimeObjects() — generated by `ork generate registry`.
// Keyed by schema.GroupVersionKind, set during Katalog validation.
//
// ObjectRegistry + ListRegistry — concrete type constructors for typed mode.
// HookRegistry                  — hook factories, keyed by GVK.
// ReconcilerRegistry            — custom constructor functions, keyed by GVK.

var ObjectRegistry = map[schema.GroupVersionKind]func() runtime.Object{}
var ListRegistry = map[schema.GroupVersionKind]func() runtime.Object{}
var HookRegistry = map[schema.GroupVersionKind]func() domain.AnyReconcileHooks{}
var ReconcilerRegistry = map[schema.GroupVersionKind]NewReconcilerFunc{}

// ── ReconcilerMode ────────────────────────────────────────────────────────────

// ReconcilerMode controls how the GenericReconciler works with objects.
//
//   - typed:        Requires compiled API types via apiTypes.location.
//     Full type safety. Deep copy via generated DeepCopy methods.
//     Required for Go mode hooks that reference typed fields.
//
//   - unstructured: No compiled types needed. Objects are map[string]interface{}.
//     Works with any CRD without code generation.
//     Required for declarative hook templates (onCreate, onDelete, etc.)
//     because templates resolve fields at runtime via path expressions.
//
// Default is "typed" when apiTypes.location is set, "unstructured" otherwise.
type ReconcilerMode string

const (
	ReconcilerModeTyped        ReconcilerMode = "typed"
	ReconcilerModeUnstructured ReconcilerMode = "unstructured"
)

// ── APITypes ──────────────────────────────────────────────────────────────────
// Mirrors the apiTypes block in crd-katalog.yaml.
// Required for typed mode. Optional for unstructured mode — only Group, Version,
// Kind, and Plural are needed (for informer registration via dynamic client).
// ork generate reads this block to emit registry entries.

type APITypes struct {
	// Go type names — used by ork generate to emit ObjectRegistry entries.
	// Required for typed mode. Not needed for unstructured mode.
	Object string `yaml:"object" validate:"omitempty"` // e.g. "Project"
	List   string `yaml:"list"   validate:"omitempty"` // e.g. "ProjectList"

	// Import alias — optional. Auto-derived from Location if not set.
	// e.g. "projv1" → import projv1 "github.com/.../project/v1alpha1"
	Alias string `yaml:"alias" validate:"omitempty"`

	// GVK fields — required in all modes for informer and registry keying.
	Group   string `yaml:"group"   validate:"required,hostname_rfc1123"`
	Version string `yaml:"version" validate:"required"`
	Kind    string `yaml:"kind"    validate:"required"`
	Plural  string `yaml:"plural"  validate:"required"`

	// APIPath — defaults to /apis. Override only for core Kubernetes types (/api).
	APIPath string `yaml:"apiPath" validate:"omitempty"`

	// Location — fully qualified Go import path.
	// e.g. "github.com/ialexeze/orkestra/api/types/project/v1alpha1"
	// Required for typed mode. Used by ork generate for import + scheme registration.
	// Not needed for unstructured mode.
	Location string `yaml:"location" validate:"omitempty"`
}

// ── Queue ─────────────────────────────────────────────────────────────────────

type Queue struct {
	// Default: true — uses shared default workqueue instead of per-CRD queue.
	// Suitable for low-volume CRDs or when queue isolation is not required.
	Default bool `yaml:"default"`

	// MaxQueueDepth — per-CRD queue depth limit.
	// 0 → uses Orkestra-level default (MAX_QUEUE_DEPTH env var).
	MaxQueueDepth int `yaml:"maxQueueDepth" validate:"omitempty,gte=0"`

	// DegradeThreshold — consecutive reconcile failures before CRD is marked degraded.
	// 0 → uses Orkestra-level default.
	DegradeThreshold int `yaml:"degradeThreshold" validate:"omitempty,gte=0"`
}

// ── Hook templates ────────────────────────────────────────────────────────────
// Declarative resource templates — used when reconciler.mode: unstructured.
// ork generate reads these and emits the corresponding hook implementations
// by pulling resource templates from the OrkestraRegistry.
//
// Field values support Go text/template expressions against the CR object:
//   Static:  replicas: 3
//   Dynamic: replicas: "{{ .spec.replicas }}"
//            name:     "{{ .metadata.name }}-app"
//            namespace:"{{ .metadata.namespace }}"
//
// All created resources are owned by the CR — cascade deletion is automatic.

// ResourceLabel is a single key-value label or annotation pair.
type ResourceLabel struct {
	Key   string `yaml:"key"   validate:"required"`
	Value string `yaml:"value" validate:"required"`
}

// ResourceRequirements mirrors Kubernetes resource requests/limits.
type ResourceRequirements struct {
	Requests map[string]string `yaml:"requests" validate:"omitempty"` // e.g. cpu: "100m"
	Limits   map[string]string `yaml:"limits"   validate:"omitempty"` // e.g. memory: "128Mi"
}

// DeploymentTemplate declares a Deployment to create/reconcile.
type DeploymentTemplate struct {
	// Name of the Deployment. Supports template expressions.
	// Default: "{{ .metadata.name }}"
	Name string `yaml:"name" validate:"omitempty"`

	// Replicas — number of pod replicas. Supports template expressions.
	// e.g. replicas: 3  or  replicas: "{{ .spec.replicas }}"
	Replicas string `yaml:"replicas" validate:"omitempty"`

	// Image — container image. Supports template expressions.
	// e.g. image: nginx:1.25  or  image: "{{ .spec.image }}"
	Image string `yaml:"image" validate:"omitempty"`

	// Port — container port.
	Port int `yaml:"port" validate:"omitempty"`

	// Namespace — target namespace. Defaults to CR namespace.
	Namespace string `yaml:"namespace" validate:"omitempty"`

	// Labels applied to the Deployment and its pods.
	Labels []ResourceLabel `yaml:"labels" validate:"omitempty"`

	// Annotations applied to the Deployment.
	Annotations []ResourceLabel `yaml:"annotations" validate:"omitempty"`

	// Resources — CPU and memory requests/limits.
	Resources *ResourceRequirements `yaml:"resources" validate:"omitempty"`
}

// ServiceTemplate declares a Service to create/reconcile.
type ServiceTemplate struct {
	Name       string          `yaml:"name"      validate:"omitempty"`
	Type       string          `yaml:"type"      validate:"omitempty"` // ClusterIP, NodePort, LoadBalancer
	Port       int             `yaml:"port"      validate:"omitempty"`
	TargetPort int             `yaml:"targetPort" validate:"omitempty"`
	Namespace  string          `yaml:"namespace" validate:"omitempty"`
	Labels     []ResourceLabel `yaml:"labels"    validate:"omitempty"`
}

// PodTemplate declares a Pod to create.
// For long-running workloads prefer DeploymentTemplate.
type PodTemplate struct {
	Name        string                `yaml:"name"        validate:"omitempty"`
	Replicas    int                   `yaml:"replicas"    validate:"omitempty"`
	Image       string                `yaml:"image"       validate:"omitempty"`
	Namespace   string                `yaml:"namespace"   validate:"omitempty"`
	Labels      []ResourceLabel       `yaml:"labels"      validate:"omitempty"`
	Annotations []ResourceLabel       `yaml:"annotations" validate:"omitempty"`
	Resources   *ResourceRequirements `yaml:"resources"   validate:"omitempty"`
}

// JobTemplate declares a Job to run.
type JobTemplate struct {
	Name         string          `yaml:"name"         validate:"omitempty"`
	Image        string          `yaml:"image"        validate:"omitempty"`
	Command      []string        `yaml:"command"      validate:"omitempty"`
	Args         []string        `yaml:"args"         validate:"omitempty"`
	BackoffLimit int             `yaml:"backoffLimit" validate:"omitempty"`
	Namespace    string          `yaml:"namespace"    validate:"omitempty"`
	Labels       []ResourceLabel `yaml:"labels"       validate:"omitempty"`
}

// CronJobTemplate declares a CronJob to create/reconcile.
type CronJobTemplate struct {
	Name      string          `yaml:"name"      validate:"omitempty"`
	Schedule  string          `yaml:"schedule"  validate:"required"` // e.g. "0 * * * *"
	Image     string          `yaml:"image"     validate:"omitempty"`
	Command   []string        `yaml:"command"   validate:"omitempty"`
	Namespace string          `yaml:"namespace" validate:"omitempty"`
	Labels    []ResourceLabel `yaml:"labels"    validate:"omitempty"`
}

// ConfigMapTemplate declares a ConfigMap to create/reconcile.
type ConfigMapTemplate struct {
	Name      string            `yaml:"name"      validate:"omitempty"`
	Namespace string            `yaml:"namespace" validate:"omitempty"`
	Data      map[string]string `yaml:"data"      validate:"omitempty"`
	Labels    []ResourceLabel   `yaml:"labels"    validate:"omitempty"`
}

// ServiceAccountTemplate declares a ServiceAccount to create/reconcile.
type ServiceAccountTemplate struct {
	Name      string          `yaml:"name"      validate:"omitempty"`
	Namespace string          `yaml:"namespace" validate:"omitempty"`
	Labels    []ResourceLabel `yaml:"labels"    validate:"omitempty"`
}

// HookTemplates declares the resources to create/reconcile/delete at each lifecycle event.
// All fields are optional — declare only what you need.
// Resources not declared here are not managed by Orkestra.
//
// Lifecycle mapping:
//
//	onCreate   → called when a CR is created (first reconcile, object has no status)
//	onReconcile → called on every reconcile — use for drift correction
//	onDelete   → called when a CR is being deleted (DeletionTimestamp set)
//	            runs before finalizer removal
//
// For most cases:
//   - Declare resources under onCreate — Orkestra creates them and reconciles
//     them back if deleted (via onReconcile drift detection)
//   - Declare cleanup under onDelete only for resources that need special handling
//     (most resources are cleaned up automatically via owner references)
type HookTemplates struct {
	Deployments     []DeploymentTemplate     `yaml:"deployments"    validate:"omitempty"`
	Services        []ServiceTemplate        `yaml:"services"       validate:"omitempty"`
	Pods            []PodTemplate            `yaml:"pods"           validate:"omitempty"`
	Jobs            []JobTemplate            `yaml:"jobs"           validate:"omitempty"`
	CronJobs        []CronJobTemplate        `yaml:"cronJobs"       validate:"omitempty"`
	ConfigMaps      []ConfigMapTemplate      `yaml:"configMaps"     validate:"omitempty"`
	ServiceAccounts []ServiceAccountTemplate `yaml:"serviceAccounts" validate:"omitempty"`
}

// ── ReconcilerConfig ──────────────────────────────────────────────────────────

type ReconcilerConfig struct {
	// ── Both modes ────────────────────────────────────────────────────────────

	// Default: true  → GenericReconciler. HookFactory optional. Mode controls typed vs unstructured.
	// Default: false → Custom reconciler. Constructor required.
	Default bool `yaml:"default" validate:"omitempty"`

	// Mode controls how objects are handled at runtime.
	//
	//   typed        — requires compiled API types via apiTypes.location.
	//                  Full type safety. Required for Go hooks referencing typed fields.
	//                  This is the default when apiTypes.location is set.
	//
	//   unstructured — no compiled types needed. Works with any CRD.
	//                  Required for declarative hook templates (onCreate, onDelete, etc.)
	//                  Fields accessed via path expressions: "{{ .spec.replicas }}"
	//
	// When mode is omitted:
	//   - If apiTypes.location is set → typed
	//   - If apiTypes.location is empty → unstructured
	Mode ReconcilerMode `yaml:"mode" validate:"omitempty,oneof=typed unstructured"`

	// Finalizers — per-CRD finalizers. Overrides the Katalog-level finalizer.
	// Applied by GenericReconciler on create, stripped before delete.
	Finalizers []string `yaml:"finalizers" validate:"omitempty"`

	// ── YAML mode — declarative location declarations ─────────────────────────
	// Read by ork generate to emit registry.go entries.
	// Read by addHooks/addReconcilers during Katalog validation to wire
	// HookFactory and Constructor from the generated registries.

	// Hooks — declares where a Go hook function lives (typed or unstructured).
	// Only used when Default: true.
	// For declarative resource templates, use OnCreate/OnReconcile/OnDelete instead.
	Hooks *HookDeclaration `yaml:"hooks" validate:"omitempty"`

	// ConstructorDecl — declares where a custom reconciler constructor lives.
	// Only used when Default: false.
	ConstructorDecl *ConstructorDeclaration `yaml:"constructor" validate:"omitempty"`

	// ── Declarative hook templates (unstructured mode only) ───────────────────
	// Declare resources to create/reconcile/delete at each lifecycle event.
	// ork generate reads these and emits hook implementations from OrkestraRegistry templates.
	// Not compatible with Default: false or mode: typed.
	//
	// Example:
	//   onCreate:
	//     deployments:
	//       - name: "{{ .metadata.name }}-app"
	//         replicas: "{{ .spec.replicas }}"
	//         image: "{{ .spec.image }}"
	//     services:
	//       - port: 8080
	OnCreate    *HookTemplates `yaml:"onCreate"    validate:"omitempty"`
	OnReconcile *HookTemplates `yaml:"onReconcile" validate:"omitempty"`
	OnDelete    *HookTemplates `yaml:"onDelete"    validate:"omitempty"`

	// ── Go mode — function references set directly ────────────────────────────
	// Never set from YAML (yaml:"-").
	// In YAML mode: populated by addHooks/addReconcilers after registry lookup.
	// In Go mode: set directly in BuildKatalogFromGo().

	// HookFactory — called once at startCRDWorkers time to get typed hooks.
	// nil → GenericReconciler runs without hooks: finalizers, events, metrics only.
	HookFactory func() domain.AnyReconcileHooks `yaml:"-"`

	// Constructor — called once at startCRDWorkers time to build a custom reconciler.
	// Must not be nil when Default: false — enforced by Katalog validation.
	Constructor NewReconcilerFunc `yaml:"-"`
}

// HookDeclaration declares where a Go hook function lives.
// Used by ork generate to emit HookRegistry entries.
type HookDeclaration struct {
	Location string `yaml:"location" validate:"required"`  // Go import path — local or remote
	Function string `yaml:"function" validate:"required"`  // exported func matching func() domain.AnyReconcileHooks
	Alias    string `yaml:"alias"    validate:"omitempty"` // import alias — auto-derived if omitted
}

// ConstructorDeclaration declares where a custom reconciler constructor lives.
// Used by ork generate to emit ReconcilerRegistry entries.
type ConstructorDeclaration struct {
	Location string `yaml:"location" validate:"required"`  // Go import path — local or remote
	Function string `yaml:"function" validate:"required"`  // exported func matching NewReconcilerFunc
	Alias    string `yaml:"alias"    validate:"omitempty"` // import alias — auto-derived if omitted
}

// ── CRDEntry ──────────────────────────────────────────────────────────────────
// One entry per CRD in the Katalog.
// YAML fields populated by the parser or by BuildKatalogFromGo().
// Fields tagged yaml:"-" are Go-only — set at runtime, never from YAML.

type CRDEntry struct {
	// ── Identity ──────────────────────────────────────────────────────────────
	Name        string `yaml:"name"        validate:"required,hostname_rfc1123"`
	Enabled     bool   `yaml:"enabled"`
	Critical    bool   `yaml:"critical"` // Orkestra marks itself degraded if this CRD degrades
	Description string `yaml:"description" validate:"omitempty"`

	// ── API Types ─────────────────────────────────────────────────────────────
	// Mirrors the apiTypes block in YAML.
	// Required for typed mode. In unstructured mode only Group/Version/Kind/Plural needed.
	APITypes APITypes `yaml:"apiTypes" validate:"required"`

	// ── Runtime objects ───────────────────────────────────────────────────────
	// Go mode  — set directly in BuildKatalogFromGo().
	// YAML typed mode — populated by addRuntimeObjects() from ObjectRegistry/ListRegistry.
	// YAML unstructured mode — uses *unstructured.Unstructured, no registry lookup needed.
	// Never set from YAML directly.
	ObjectGoMode       runtime.Object        `yaml:"-"`
	ListObjectGoMode   runtime.Object        `yaml:"-"`
	ObjectYamlMode     func() runtime.Object `yaml:"-"`
	ListObjectYamlMode func() runtime.Object `yaml:"-"`

	// Scheme registration function — generated by controller-gen per API type.
	// Go mode + YAML typed mode: required for REST client decoding.
	// YAML unstructured mode: not needed — dynamic client bypasses scheme.
	Scheme func(s *runtime.Scheme) error `yaml:"-"`

	// ── Computed GVK/GVR ─────────────────────────────────────────────────────
	// Populated by setGroupVersionKind() during Katalog validation.
	// Derived from APITypes — never set manually.
	GroupVersion         *schema.GroupVersion        `yaml:"-"`
	GroupVersionKind     schema.GroupVersionKind     `yaml:"-"`
	GroupVersionResource schema.GroupVersionResource `yaml:"-"`

	// ── Scope ─────────────────────────────────────────────────────────────────
	Namespaced bool   `yaml:"namespaced"`
	Namespace  string `yaml:"namespace" validate:"omitempty"`

	// ── Runtime behaviour ─────────────────────────────────────────────────────
	Workers   int           `yaml:"workers"   validate:"omitempty,gte=1,lte=50"`
	Resync    time.Duration `yaml:"resync"    validate:"omitempty"`
	DependsOn []string      `yaml:"dependsOn"`

	// ── Reconciler + Queue ────────────────────────────────────────────────────
	ReconcilerConfig ReconcilerConfig `yaml:"reconciler"`
	Queue            Queue            `yaml:"queue"`

	// ── Reegistries ────────────────────────────────────────────────────
	ObjectRegistry     map[schema.GroupVersionKind]func() runtime.Object
	ListRegistry       map[schema.GroupVersionKind]func() runtime.Object
	HookRegistry       map[schema.GroupVersionKind]func() domain.AnyReconcileHooks
	ReconcilerRegistry map[schema.GroupVersionKind]NewReconcilerFunc
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// GetRuntimeObjects returns the correct object and list for the given mode.
// YAML mode uses ObjectYamlMode/ListObjectYamlMode populated by addRuntimeObjects().
// Go mode uses ObjectGoMode/ListObjectGoMode set in BuildKatalogFromGo().
func (c *CRDEntry) GetRuntimeObjects(mode string) (runtime.Object, runtime.Object) {
	if mode == "yaml" {
		return c.ObjectYamlMode(), c.ListObjectYamlMode()
	}
	return c.ObjectGoMode, c.ListObjectGoMode
}

// SetMaxQueueDepth returns the per-CRD depth if set, otherwise the Orkestra default.
func (c *CRDEntry) SetMaxQueueDepth(def int) int {
	if c.Queue.MaxQueueDepth == 0 {
		return def
	}
	return c.Queue.MaxQueueDepth
}

// SetWorkers returns the per-CRD worker count if set, otherwise the Orkestra default.
func (c *CRDEntry) SetWorkers(def int) int {
	if c.Workers == 0 {
		return def
	}
	return c.Workers
}

// IsUnstructured returns true if this CRD uses unstructured mode.
// Unstructured mode is used when mode: unstructured is declared, or when
// apiTypes.location is empty (no compiled types available).
func (c *CRDEntry) IsUnstructured() bool {
	if c.ReconcilerConfig.Mode == ReconcilerModeUnstructured {
		return true
	}
	if c.ReconcilerConfig.Mode == "" && c.APITypes.Location == "" {
		return true
	}
	return false
}

// GVK returns the computed GroupVersionKind.
func (c *CRDEntry) GVK() schema.GroupVersionKind {
	return c.GroupVersionKind
}

// GVR returns the computed GroupVersionResource.
func (c *CRDEntry) GVR() schema.GroupVersionResource {
	return c.GroupVersionResource
}
