// pkg/runtime/zz_generated_runtime_registry.go
// Code generated by "ork generate runtime" on 2026-03-19T12:05:02Z. DO NOT EDIT.
// Re-generate by running: ork generate runtime --katalog <path-or-url>
package runtime

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func RegisterRuntimeObjects() {}

func RegisterTypedScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
	return scheme, nil
}
