# https://orkestra.sh/docs/reference/schema/e2e/
apiVersion: orkestra.orkspace.io/v1
kind: E2E
metadata:
  name: namespace-provisioner-suite
  description: >
    Suite for the namespace-provisioner use case. Runs all four examples
    sequentially in the same cluster.

imports:
  - ./01-explicit/e2e.yaml
  - ./02-profiles/e2e.yaml
  - ./03-user-defined-profiles/e2e.yaml
  - ./04-motif-profiles/e2e.yaml
