apiVersion: reconciler.orkestra.io/v1alpha1
kind: ReconcilerProbe
metadata:
  name: probe
  namespace: default
spec:
  image: nginx:1.25
  replicas: 1
  port: 8080
  tier: premiumc
  schedule: "*/15 * * * *"
  extraLabels:
    - "team=platform"
    - "env=ci"
