apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-service
  namespace: default
  labels:
    orkestra.io/katalog: configmap-manager
data:
  image: "nginx:latest"
  replicas: "3"
  username: "payments-user"
  region: "us-east-1"
