apiVersion: demo.orkestra.io/v1
kind: Workload
metadata:
  name: worker
  namespace: default
spec:
  image: nginx:1.25
  replicas: 3
  concurrencyPolicy: Forbid
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
