apiVersion: orkestra.orkspace.io/v1
kind: Simulate
metadata:
  name: resilience-simulate

imports:
  - ./01-admission-protection/simulate.yaml
  - ./02-crd-missing-recovery/simulate.yaml
  - ./03-leader-failover/simulate.yaml
