package internal

import (
	"context"
	"strings"

	"github.com/ialexeze/orkestra/domain"
	"github.com/ialexeze/orkestra/pkg/event"
	"github.com/ialexeze/orkestra/pkg/health"
	"github.com/ialexeze/orkestra/pkg/informer"
	"github.com/ialexeze/orkestra/pkg/katalog"
	"github.com/ialexeze/orkestra/pkg/konfig"
	"github.com/ialexeze/orkestra/pkg/kontroller"
	"github.com/ialexeze/orkestra/pkg/kubeclient"
	"github.com/ialexeze/orkestra/pkg/logger"
	ork "github.com/ialexeze/orkestra/pkg/orkestra"
	"github.com/ialexeze/orkestra/pkg/queue"
	"github.com/ialexeze/orkestra/pkg/reconciler"
	"github.com/ialexeze/orkestra/pkg/utils"
)

type OrkestraKfg struct {
	kontroller *kontroller.DependencyKontroller
	event      *event.Event
	kube       *kubeclient.Kubeclient
	orkestra   *ork.Orkestra
	komp       *[]domain.Komponent
}

// konstructOrkestra wires the entire Orkestra runtime.
//
// Sequence:
//  1. Load and validate the Katalog — only enabled, validated CRD entries reach here
//  2. Register schemes so Go types can decode API server responses
//  3. Create all komponents (nothing starts yet — orkestra starts them in order)
//  4. Register per-CRD client providers, informers, and reconciler factories
//  5. Register health and Katalog API routes
//  6. Hand everything to orkestra
//
// IMPORTANT: Nothing that requires a live kube connection runs here.
// Reconciler factories are closures — called in startCRDWorkers after
// orkestra.Start() has initialised kube, ev, and all REST clients.
func konstructOrkestra(kfg *konfig.Konfig, ctx context.Context) *OrkestraKfg {

	// ── 1. Katalog ────────────────────────────────────────────────────────────
	crdKatalog := katalog.NewKatalog(kfg.Katalog().Mode, kfg.Katalog().Path)

	// ── 2. Scheme ─────────────────────────────────────────────────────────────
	// Registers all CRD Go types so the REST client can decode API server responses.
	// AddToScheme is generated by controller-gen for each API type.
	scheme, err := katalog.NewSchemeRegistry(crdKatalog)
	if err != nil {
		logger.Fatal().Err(err).Msg("failed to build scheme registry")
	}

	// ── 3. Core komponents ────────────────────────────────────────────────────
	// None of these are started here. Orkestra calls Start() in declaration order.

	// Health server — created first so routes can be registered before Start().
	hs := health.NewHealthServer(
		kfg.App().Name,
		kfg.Health().Port,
		kfg.App().LogLevel,
	)

	// Kubeclient — not live until orkestra calls kube.Start().
	kube := kubeclient.NewKubeclient(kubeclient.Config{
		Kubeconfig: kfg.Cluster().KubekonfigPath,
		Masterurl:  kfg.Cluster().MasterURL,
		Scheme:     scheme,
	})

	// Event recorder — wraps kube, also not live until kube.Start().
	ev := event.NewEvent(kube)

	// Default workqueue — shared fallback for CRDs with Queue.Default = true.
	defaultWq := queue.NewWorkqueue()

	// Per-CRD queue registry — each CRD gets an isolated queue.
	queueRegistry := queue.NewQueueRegistry()

	// ── 4a. Client provider ───────────────────────────────────────────────────
	// Registers a REST client constructor per CRD type.
	// Constructors are deferred — executed when the provider is first used.
	provider := kube.ClientProvider()

	for _, crd := range crdKatalog.Enabled() {
		crd := crd // capture — closure must own its own crd value
		object, list := crd.GetRuntimeObjects(kfg.Mode())

		logger.Debug().
			Str("gvk", utils.SetGroupVersionKindObj(crd.GroupVersionKind)).
			Str("mode", kfg.Mode()).
			Msg("registering CRD client provider")

		provider.Register(object, func(k *kubeclient.Kubeclient) (informer.GenericClient, error) {
			return k.NewClient(list, kubeclient.CRDInfo{
				Kind:         crd.APITypes.Kind,
				Group:        crd.APITypes.Group,
				Version:      crd.APITypes.Version,
				APIPath:      crd.APITypes.APIPath,
				GroupVersion: crd.GroupVersion,
				Plural:       crd.APITypes.Plural,
				Namespace:    crd.Namespace,
				Namespaced:   crd.Namespaced,
			})
		})
	}

	// ── 4b. Shared informer factory ───────────────────────────────────────────
	// Routes API server events into the correct per-CRD queue via handleEvent.
	// Not started here — infFactory.Start() is called by orkestra.
	infFactory := informer.SharedInformerFactory(
		provider,
		queueRegistry,
		defaultWq,
		scheme,
		kfg.Cluster().Namespace,
		kfg.Cluster().DefaultResync,
	)

	// ── 4c. Kontroller registry + per-CRD wiring ──────────────────────────────
	// Registers informers and reconciler factories per CRD.
	// Factories are closures — NewGenericReconciler / Constructor called
	// only after orkestra starts, guaranteeing kube and ev are live.
	ktrlRegistry := kontroller.NewKontrollerRegistry()

	logger.Debug().Msg("wiring CRDs into kontroller registry...")

	for _, crd := range crdKatalog.Enabled() {
		crd := crd
		gvk := utils.SetGroupVersionKindObj(crd.GroupVersionKind)
		gvr := crd.GroupVersionResource

		// GetRuntimeObjects abstracts Go vs YAML mode —
		// ObjectYamlMode is already populated by addRuntimeObjects() during validation.
		object, _ := crd.GetRuntimeObjects(kfg.Mode())

		wq := queueRegistry.Register(gvk, crd.SetMaxQueueDepth(
			kfg.Katalog().DefaultMaxQueueDepth,
		))

		opts := informer.Options{
			Name:   crd.APITypes.Kind,
			Resync: crd.Resync,
		}

		if crd.Queue.Default {
			logger.Debug().Str("gvk", gvk).Msg("using default workqueue")
			opts.Wq = nil
		} else {
			opts.Wq = wq
		}

		inf := infFactory.For(object, ctx, opts)

		crdInfo := reconciler.CRDInfo{
			Kind:       crd.APITypes.Kind,
			GVK:        gvk,
			GVR:        gvr,
			Finalizers: crd.ReconcilerConfig.Finalizers,
		}
		infCopy := inf

		var factory func() domain.Reconciler

		if crd.ReconcilerConfig.Default {
			// ObjectYamlMode / ObjectGoMode already set — GetRuntimeObjects handles mode.
			// We need a domain.Object factory for GenericReconciler.
			// object is already the correct concrete type for this CRD.
			objCopy := object // capture the concrete runtime.Object for this CRD

			var anyHooks domain.AnyReconcileHooks
			if crd.ReconcilerConfig.HookFactory != nil {
				anyHooks = crd.ReconcilerConfig.HookFactory()
			}

			logger.Debug().Str("gvk", gvk).Msg("wiring GenericReconciler factory")

			factory = func() domain.Reconciler {
				return reconciler.NewGenericReconciler(
					crdInfo,
					infCopy,
					ev,
					kube,
					anyHooks,
					func() domain.Object {
						// DeepCopyObject gives us a fresh zero-value instance
						// of the correct concrete type — no registry lookup needed.
						return objCopy.DeepCopyObject().(domain.Object)
					},
				)
			}

		} else {
			if crd.ReconcilerConfig.Constructor == nil {
				logger.Fatal().
					Str("gvk", gvk).
					Msg("reconciler.default is false but no Constructor provided")
			}

			logger.Debug().Str("gvk", gvk).Msg("wiring custom reconciler factory")

			factory = func() domain.Reconciler {
				return crd.ReconcilerConfig.Constructor(kube, infCopy, ev)
			}
		}

		ktrlRegistry.Register(gvk, crd, inf, factory)
		logger.Debug().Str("gvk", gvk).Msg("CRD registered")
	}
	// ── 5a. Per-CRD health map ────────────────────────────────────────────────
	// Built before routes and before NewDependencyKontroller so all three
	// share pointers to the same CRDHealth instances.
	//   startCRDWorkers  → RecordSuccess / RecordFailure per reconcile
	//   route handlers   → read health state on HTTP request
	crdHealthMap := make(map[string]*kontroller.CRDHealth)
	for _, crd := range crdKatalog.Enabled() {
		gvk := utils.SetGroupVersionKindObj(crd.GroupVersionKind)
		crdHealthMap[gvk] = kontroller.NewCRDHealth(crd.Name)
	}

	// ── 5b. Health and Katalog API routes ─────────────────────────────────────
	// All routes must be registered before hs.Start() — the HTTP server
	// uses hs.mux which is the same mux Register() writes to.
	for _, crd := range crdKatalog.Enabled() {
		gvk := utils.SetGroupVersionKindObj(crd.GroupVersionKind)
		crdHealth := crdHealthMap[gvk]
		crdName := strings.ToLower(crd.Name)

		// GET /katalog/{crd}/health — 200 healthy, 503 degraded
		hs.Register(
			"/katalog/"+crdName+"/health",
			kontroller.BuildCRDHealthHandler(crd.Name, crdHealth),
		)

		// GET /katalog/{crd} — CRD config + live reconcile stats
		hs.Register(
			"/katalog/"+crdName,
			kontroller.BuildCRDInfoHandler(crd, crdHealth),
		)

		logger.Debug().
			Str("health", "/katalog/"+crdName+"/health").
			Str("info", "/katalog/"+crdName).
			Msg("registered CRD health routes")
	}

	// GET /katalog — aggregate view: all CRDs, dependency graph, health summary
	hs.Register("/katalog", kontroller.BuildKatalogHandler(crdKatalog, crdHealthMap))

	// ── 6. Komponent list ─────────────────────────────────────────────────────
	// Orkestra starts these in order. Shutdown runs in reverse.
	komponents := []domain.Komponent{
		hs,            // 1. health server  — routes already registered above
		kube,          // 2. kubeclient     — REST config, dynamic client, clientset
		ev,            // 3. event recorder — depends on kube being started
		queueRegistry, // 4. per-CRD queues
		defaultWq,     // 5. default fallback queue
		infFactory,    // 6. informer factory — starts informers, closes ready channel
	}

	// ── 7. Dependency kontroller ──────────────────────────────────────────────
	// Starts CRD workers in topological dependency order.
	// Calls ReconcilerFactory() per CRD after infFactory is live.
	// Passes crdHealthMap — health state updated per reconcile result.
	ktrl := kontroller.NewDependencyKontroller(
		kube,
		infFactory,
		ktrlRegistry,
		ev,
		queueRegistry,
		defaultWq,
		crdHealthMap,
		kfg.Cluster().DefaultWorkers,
		katalog.NewDependencyGraph(crdKatalog),
		&kontroller.BannerKonfig{
			Katalog:    crdKatalog.Enabled(),
			Konfig:     kfg,
			Komponents: komponents,
			Leader:     "",
		},
	)

	// Kontroller is last — depends on everything above being started first.
	komponents = append(komponents, ktrl)

	// ── 8. Orkestra ────────────────────────────────────────────────────────────
	// Owns the full lifecycle of all komponents.
	// Start  : sequential, in registration order.
	// Shutdown: reverse order, on OS signal or fatal error.
	o := ork.NewOrkestra(kfg.Cluster().DefaultResync, kfg.App().LogLevel)
	o.Register(komponents)

	return &OrkestraKfg{
		event:      ev,
		kontroller: ktrl,
		kube:       kube,
		komp:       &komponents,
		orkestra:   o,
	}
}
