// internal/construct_security.go
//
// Security wiring — called from konstructOrkestra after the HealthServer
// is constructed and before Orkestra starts.
//
// Handles:
//
//  1. TLS certificate generation — when deletion protection, admission webhooks,
//     or conversion webhooks are enabled and no explicit cert is configured.
//     Uses GenerateTLSBundle from run_secrets_tls.go. Stores in orkestra-tls Secret.
//
//  2. CRD conversion webhook patch — when a CRD declares conversion.updateCRD: true,
//     Orkestra patches the CRD's spec.conversion.webhook.clientConfig.caBundle with
//     the CA certificate from the generated (or configured) TLS bundle.
//
// All operations fatal-log on failure — if security cannot be applied, the
// operator cannot function correctly.
package internal

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/orkspace/orkestra/pkg/katalog"
	"github.com/orkspace/orkestra/pkg/konfig"
	"github.com/orkspace/orkestra/pkg/kubeclient"
	"github.com/orkspace/orkestra/pkg/logger"
	"github.com/orkspace/orkestra/pkg/reconciler"
	corev1 "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

const (
	// orkestraTLSSecretName is the default Secret name for Orkestra's TLS cert.
	orkestraTLSSecretName = "orkestra-tls"

	// Default cert validity — 1 year.
	defaultCertValidFor = "1y"
)

// ensureSecurity applies TLS certificates when security features
// are enabled in the Katalog. Called synchronously before Start().
//
// Order:
//  1. TLS  — must succeed before the HTTPS server starts (webhook endpoint)
//  2. CRD patch — patches caBundle into CRDs that declare updateCRD: true
func ensureSecurity(
	ctx context.Context,
	kfg *konfig.Konfig,
	kat *katalog.Katalog,
	kube *kubeclient.Kubeclient,
) (tlsCertFile, tlsKeyFile string, err error) {
	namespace := kfg.Cluster().Namespace

	// ── TLS certificate management ────────────────────────────────────────
	// TLS is required whenever deletion protection, admission webhooks, or
	// conversion webhooks are enabled. If the user has provided TLS_CERT and
	// TLS_KEY those are used as-is. Otherwise Orkestra generates self-signed
	// certs and stores them in the orkestra-tls Secret.
	needsTLS := kat.NeedsCertificates()

	if !needsTLS {
		return "", "", nil
	}

	configuredCert := kfg.Security().Webhooks.TLSCert
	configuredKey := kfg.Security().Webhooks.TLSKey

	if configuredCert != "" && configuredKey != "" {
		// User provided certs — use them as-is; no CRD patch (user manages caBundle)
		logger.Info().
			Str("cert", configuredCert).
			Msg("security: using provided TLS certificates")
		return configuredCert, configuredKey, nil
	}

	// No explicit cert configured — generate self-signed
	logger.Info().Msg("security: generating TLS certificates")

	serviceName := kat.DeletionProtectionServiceName()
	svcNamespace := namespace

	bundle, err := reconciler.GenerateTLSBundle(
		serviceName+"."+svcNamespace+".svc",
		[]string{
			serviceName,
			serviceName + "." + svcNamespace,
			serviceName + "." + svcNamespace + ".svc",
			serviceName + "." + svcNamespace + ".svc.cluster.local",
		},
		defaultCertValidFor,
	)
	if err != nil {
		logger.Fatal().Err(err).Msg("security: failed to generate TLS certificates")
	}

	certFile, keyFile, writeErr := writeTLSToFiles(bundle)
	if writeErr != nil {
		logger.Fatal().Err(writeErr).Msg("security: failed to write TLS certificates to files")
	}

	// Store in the orkestra-tls Secret for the webhook caBundle
	if err := storeTLSSecret(kfg, ctx, kube, namespace, orkestraTLSSecretName, bundle); err != nil {
		logger.Warn().Err(err).
			Str("secret", orkestraTLSSecretName).
			Msg("security: failed to store TLS secret — webhook caBundle may be unavailable")
	}

	logger.Info().
		Str("cert", certFile).
		Str("secret", orkestraTLSSecretName).
		Msg("security: TLS certificates generated and stored")

	// ── 2. CRD conversion webhook patch ──────────────────────────────────────
	// For each enabled CRD that declares conversion.updateCRD: true, patch the
	// CRD's spec.conversion.webhook.clientConfig.caBundle with the generated CA.
	if err := patchConversionCRDs(ctx, kube, kat, bundle.CACertPEM, serviceName, svcNamespace); err != nil {
		logger.Warn().Err(err).Msg("security: some CRD conversion patches failed")
	}

	// Update katalog field - needed for deciding crd patching rbac
	kat.AutogeneratedCerts.Store(true)

	return certFile, keyFile, nil
}

// patchConversionCRDs patches the caBundle into every enabled CRD that has
// conversion.updateCRD: true. Each patch is best-effort; errors are collected
// and returned as a combined error so all CRDs are attempted.
func patchConversionCRDs(
	ctx context.Context,
	kube *kubeclient.Kubeclient,
	kat *katalog.Katalog,
	caCertPEM []byte,
	serviceName, serviceNamespace string,
) error {
	caBundle := base64.StdEncoding.EncodeToString(caCertPEM)
	port := int32(8443)
	path := "/convert"

	var errs []error
	for _, crd := range kat.EnabledCRDs() {
		if crd.Conversion == nil || !crd.UpdateCRDCaBundle() {
			continue
		}

		crdName := crd.APITypes.Plural + "." + crd.APITypes.Group

		// Strategic-merge patch for the conversion block
		patch := map[string]interface{}{
			"spec": map[string]interface{}{
				"conversion": map[string]interface{}{
					"strategy": "Webhook",
					"webhook": map[string]interface{}{
						"clientConfig": map[string]interface{}{
							"caBundle": caBundle,
							"service": map[string]interface{}{
								"name":      serviceName,
								"namespace": serviceNamespace,
								"path":      path,
								"port":      port,
							},
						},
						"conversionReviewVersions": []string{"v1"},
					},
				},
			},
		}

		patchBytes, err := json.Marshal(patch)
		if err != nil {
			errs = append(errs, fmt.Errorf("marshalling patch for %s: %w", crdName, err))
			continue
		}

		_, err = kube.ApiextensionsClient().
			ApiextensionsV1().
			CustomResourceDefinitions().
			Patch(ctx, crdName, types.MergePatchType, patchBytes, metav1.PatchOptions{})
		if err != nil {
			errs = append(errs, fmt.Errorf("patching CRD %s: %w", crdName, err))
			continue
		}

		logger.Info().
			Str("crd", crdName).
			Str("service", serviceName+"."+serviceNamespace+".svc").
			Msg("security: CRD conversion webhook patched with caBundle")
	}

	if len(errs) > 0 {
		return fmt.Errorf("crd patch errors: %v", errs)
	}
	return nil
}

// writeTLSToFiles writes the TLS bundle to temporary files.
// Returns the cert file path and key file path.
func writeTLSToFiles(bundle *reconciler.TLSBundle) (certFile, keyFile string, err error) {
	cert, err := os.CreateTemp("", "orkestra-tls-cert-*.pem")
	if err != nil {
		return "", "", err
	}
	if _, err := cert.Write(bundle.CertPEM); err != nil {
		return "", "", err
	}
	cert.Close()

	key, err := os.CreateTemp("", "orkestra-tls-key-*.pem")
	if err != nil {
		return "", "", err
	}
	if _, err := key.Write(bundle.KeyPEM); err != nil {
		return "", "", err
	}
	key.Close()

	return cert.Name(), key.Name(), nil
}

// storeTLSSecret creates or updates the orkestra-tls Secret with the generated
// TLS bundle. The Secret holds three keys:
//
//	tls.crt — PEM-encoded signed certificate (server cert)
//	tls.key — PEM-encoded private key
//	ca.crt  — PEM-encoded CA certificate (used as caBundle in webhook config)
func storeTLSSecret(
	kfg *konfig.Konfig,
	ctx context.Context,
	kube *kubeclient.Kubeclient,
	namespace, secretName string,
	bundle *reconciler.TLSBundle,
) error {
	client := kube.Clientset().CoreV1().Secrets(namespace)

	labels := kfg.OrkestraResourceLabels()
	labels["app.kubernetes.io/component"] = "tls"

	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      secretName,
			Namespace: namespace,
			Labels:    labels,
			Annotations: map[string]string{
				"orkestra.konductor.io/generated-at": time.Now().UTC().Format(time.RFC3339),
			},
		},
		Type: corev1.SecretTypeTLS,
		Data: map[string][]byte{
			"tls.crt": bundle.CertPEM,
			"tls.key": bundle.KeyPEM,
			"ca.crt":  bundle.CACertPEM,
		},
	}

	_, err := client.Create(ctx, secret, metav1.CreateOptions{})
	if err == nil {
		return nil
	}

	if !k8serrors.IsAlreadyExists(err) {
		return fmt.Errorf("creating tls secret %s/%s: %w", namespace, secretName, err)
	}

	existing, err := client.Get(ctx, secretName, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("getting existing tls secret %s/%s: %w", namespace, secretName, err)
	}

	secret.ResourceVersion = existing.ResourceVersion
	_, err = client.Update(ctx, secret, metav1.UpdateOptions{})
	if err != nil {
		return fmt.Errorf("updating tls secret %s/%s: %w", namespace, secretName, err)
	}

	return nil
}
