// internal/construct_security.go
//
// Security wiring — called from konstructOrkestra after the HealthServer
// is constructed and before Orkestra starts.
//
// Handles:
//
//  1. TLS certificate generation — when deletion protection, admission webhooks,
//     or conversion webhooks are enabled and no explicit cert is configured.
//     Uses certmanager.Manager to generate and store the bundle in orkestra-tls Secret.
//
//  2. CRD conversion webhook patch — when a CRD declares conversion.updateCRD: true,
//     Orkestra patches the CRD's spec.conversion.webhook.clientConfig.caBundle with
//     the CA certificate from the generated (or configured) TLS bundle.
//
// All operations fatal-log on failure — if security cannot be applied, the
// operator cannot function correctly.
package internal

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"

	"github.com/orkspace/orkestra/pkg/certmanager"
	"github.com/orkspace/orkestra/pkg/katalog"
	"github.com/orkspace/orkestra/pkg/konfig"
	"github.com/orkspace/orkestra/pkg/kubeclient"
	"github.com/orkspace/orkestra/pkg/logger"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

const (
	// defaultCertValidFor is the default certificate validity duration.
	defaultCertValidFor = "1y"
)

// ensureSecurity applies TLS certificates when security features
// are enabled in the Katalog. Called synchronously before Start().
//
// Order:
//  1. TLS  — must succeed before the HTTPS server starts (webhook endpoint)
//  2. CRD patch — patches caBundle into CRDs that declare updateCRD: true
//
// Returns the cert file path, key file path, and the cert manager (for shutdown cleanup).
func ensureSecurity(
	ctx context.Context,
	kfg *konfig.Konfig,
	kat *katalog.Katalog,
	kube *kubeclient.Kubeclient,
) (tlsCertFile, tlsKeyFile string, certMgr certmanager.Manager, err error) {
	namespace := kfg.Cluster().Namespace

	// ── Namespace labeling ────────────────────────────────────────────────
	// The deletion-protection webhook uses ObjectSelector to narrow to labeled
	// resources. Namespaces are cluster-scoped and carry no labels by default,
	// so the webhook would never fire for the Orkestra namespace unless we label
	// it ourselves. Apply the full orkestra resource label set (including
	// orkestra.io/deletion-protection) so the webhook intercepts any attempt to
	// delete this namespace.
	if err := ensureNamespaceLabeled(ctx, kube, namespace, kfg.OrkestraResourceLabels()); err != nil {
		logger.Warn().Err(err).
			Str("namespace", namespace).
			Msg("security: failed to label orkestra namespace — deletion protection will not cover it")
	}

	// ── TLS certificate management ────────────────────────────────────────
	// TLS is required whenever deletion protection, admission webhooks, or
	// conversion webhooks are enabled. If the user has provided TLS_CERT and
	// TLS_KEY those are used as-is. Otherwise Orkestra generates self-signed
	// certs and stores them in the orkestra-tls Secret.
	needsTLS := kat.NeedsCertificates()
	if !needsTLS {
		return "", "", nil, nil
	}

	configuredCert := kfg.Security().Webhooks.TLSCert
	configuredKey := kfg.Security().Webhooks.TLSKey

	if configuredCert != "" && configuredKey != "" {
		// User provided certs — use them as-is; no CRD patch (user manages caBundle)
		logger.Info().
			Str("cert", configuredCert).
			Msg("security: using provided TLS certificates")
		return configuredCert, configuredKey, nil, nil
	}

	// No explicit cert configured — generate self-signed via certmanager.
	logger.Info().Msg("security: generating TLS certificates")

	serviceName := kat.OrkestraServiceName()
	mgr := certmanager.New(kube.Clientset())

	bundle, err := mgr.EnsureCertificate(ctx, certmanager.CertificateSpec{
		ServiceName: serviceName,
		Namespace:   namespace,
		SecretName:  certmanager.DefaultTLSSecretName,
		ValidFor:    defaultCertValidFor,
		BaseLabels:  kfg.OrkestraResourceLabels(),
	})
	if err != nil {
		logger.Fatal().Err(err).Msg("security: failed to ensure TLS secret")
	}

	certFile, keyFile, writeErr := writeTLSToFiles(bundle)
	if writeErr != nil {
		logger.Fatal().Err(writeErr).Msg("security: failed to write TLS certificates to files")
	}

	logger.Info().
		Str("cert", certFile).
		Str("secret", certmanager.DefaultTLSSecretName).
		Msg("security: TLS certificates generated and stored")

	// ── 2. CRD conversion webhook patch ──────────────────────────────────────
	// For each enabled CRD that declares conversion.updateCRD: true, patch the
	// CRD's spec.conversion.webhook.clientConfig.caBundle with the generated CA.
	if err := patchConversionCRDs(ctx, kube, kat, bundle.CACertPEM, serviceName, namespace); err != nil {
		logger.Warn().Err(err).Msg("security: some CRD conversion patches failed")
	}

	// Update katalog field — needed for deciding CRD patching RBAC.
	kat.AutogeneratedCerts.Store(true)

	return certFile, keyFile, mgr, nil
}

// patchConversionCRDs patches the caBundle into every enabled CRD that has
// conversion.updateCRD: true. Each patch is best-effort; errors are collected
// and returned as a combined error so all CRDs are attempted.
func patchConversionCRDs(
	ctx context.Context,
	kube *kubeclient.Kubeclient,
	kat *katalog.Katalog,
	caCertPEM []byte,
	serviceName, serviceNamespace string,
) error {
	caBundle := base64.StdEncoding.EncodeToString(caCertPEM)
	port := int32(8443)
	path := "/convert"

	var errs []error
	for _, crd := range kat.EnabledCRDs() {
		if crd.Conversion == nil || !crd.UpdateCRDCaBundle() {
			continue
		}

		crdName := crd.APITypes.Plural + "." + crd.APITypes.Group
		storageVersion := crd.Conversion.StorageVersion

		logger.Info().Msgf("storage version: %s", storageVersion)

		patch := map[string]interface{}{
			"spec": map[string]interface{}{
				"conversion": map[string]interface{}{
					"strategy": "Webhook",
					"webhook": map[string]interface{}{
						"clientConfig": map[string]interface{}{
							"caBundle": caBundle,
							"service": map[string]interface{}{
								"name":      serviceName,
								"namespace": serviceNamespace,
								"path":      path,
								"port":      port,
							},
						},
						"conversionReviewVersions": []string{storageVersion},
					},
				},
			},
		}

		patchBytes, err := json.Marshal(patch)
		if err != nil {
			errs = append(errs, fmt.Errorf("marshalling patch for %s: %w", crdName, err))
			continue
		}

		_, err = kube.ApiextensionsClient().
			ApiextensionsV1().
			CustomResourceDefinitions().
			Patch(ctx, crdName, types.MergePatchType, patchBytes, metav1.PatchOptions{})
		if err != nil && !k8serrors.IsNotFound(err) {
			errs = append(errs, fmt.Errorf("patching CRD %s: %w", crdName, err))
			continue
		}

		logger.Info().
			Str("crd", crdName).
			Str("service", serviceName+"."+serviceNamespace+".svc").
			Msg("security: CRD conversion webhook patched with caBundle")
	}

	if len(errs) > 0 {
		return fmt.Errorf("crd patch errors: %v", errs)
	}
	return nil
}

// writeTLSToFiles writes the TLS bundle to temporary files.
// Returns the cert file path and key file path.
func writeTLSToFiles(bundle *certmanager.TLSBundle) (certFile, keyFile string, err error) {
	cert, err := os.CreateTemp("", "orkestra-tls-cert-*.pem")
	if err != nil {
		return "", "", err
	}
	if _, err := cert.Write(bundle.CertPEM); err != nil {
		return "", "", err
	}
	cert.Close()

	key, err := os.CreateTemp("", "orkestra-tls-key-*.pem")
	if err != nil {
		return "", "", err
	}
	if _, err := key.Write(bundle.KeyPEM); err != nil {
		return "", "", err
	}
	key.Close()

	return cert.Name(), key.Name(), nil
}

// ensureNamespaceLabeled patches the Orkestra namespace with the given labels
// so that the deletion-protection webhook's ObjectSelector can match it.
// Namespaces are cluster-scoped and carry no labels by default — without this
// patch the webhook rule for namespaces would never fire for this namespace.
// Uses a strategic-merge patch so existing labels are preserved.
func ensureNamespaceLabeled(ctx context.Context, kube *kubeclient.Kubeclient, namespace string, labels map[string]string) error {
	patch := map[string]interface{}{
		"metadata": map[string]interface{}{
			"labels": labels,
		},
	}
	patchBytes, err := json.Marshal(patch)
	if err != nil {
		return fmt.Errorf("marshalling namespace label patch: %w", err)
	}
	_, err = kube.Clientset().CoreV1().Namespaces().Patch(
		ctx, namespace, types.MergePatchType, patchBytes, metav1.PatchOptions{},
	)
	if err != nil && !k8serrors.IsNotFound(err) {
		return fmt.Errorf("patching namespace %s: %w", namespace, err)
	}
	return nil
}
