package internal

import (
	"context"
	"strings"

	"github.com/ialexeze/orkestra/domain"
	"github.com/ialexeze/orkestra/pkg/event"
	"github.com/ialexeze/orkestra/pkg/health"
	"github.com/ialexeze/orkestra/pkg/informer"
	"github.com/ialexeze/orkestra/pkg/katalog"
	"github.com/ialexeze/orkestra/pkg/konfig"
	"github.com/ialexeze/orkestra/pkg/kontroller"
	"github.com/ialexeze/orkestra/pkg/kubeclient"
	"github.com/ialexeze/orkestra/pkg/logger"
	"github.com/ialexeze/orkestra/pkg/merger"
	ork "github.com/ialexeze/orkestra/pkg/orkestra"
	"github.com/ialexeze/orkestra/pkg/queue"
	"github.com/ialexeze/orkestra/pkg/reconciler"
	"k8s.io/client-go/tools/cache"
)

type orkestraKfg struct {
	konfig     *konfig.Konfig
	katalog    *katalog.Katalog
	komp       *[]domain.Komponent
	event      *event.Event
	kube       *kubeclient.Kubeclient
	kontroller *kontroller.DependencyKontroller
	orkestra   *ork.Orkestra
}

// konstructOrkestra wires the entire Orkestra runtime.
//
// Sequence:
//  1. Load and validate the Katalog — only enabled, validated CRD entries reach here
//  2. Register schemes so Go types can decode API server responses
//  3. Create all komponents (nothing starts yet except 'kubeclient' — orkestra starts them in order)
//  4. Register per-CRD client providers, informers, and reconciler factories
//  5. Register health and Katalog API routes
//  6. Hand everything to orkestra
//
// IMPORTANT: Nothing that requires a live kube connection runs here.
// Reconciler factories are closures — called in startCRDWorkers after
// orkestra.Start() has initialised kube, ev, and all REST clients.
func konstructOrkestra(kfg *konfig.Konfig, m *merger.Merger, ctx context.Context) *orkestraKfg {

	// ── 1. Katalog ────────────────────────────────────────────────────────────
	kat := katalog.NewKatalog(m, kfg.Katalog().Paths...)

	// ── 2. Scheme ─────────────────────────────────────────────────────────────
	// Registers all CRD Go types so the REST client can decode API server responses.
	// AddToScheme is generated by controller-gen for each API type.
	scheme, err := katalog.NewSchemeRegistry(kat)
	if err != nil {
		logger.Fatal().Err(err).Msg("failed to build scheme registry")
	}

	// ── 3. Core komponents ────────────────────────────────────────────────────
	// None of these are started here. Orkestra calls Start() in declaration order.

	// Health server — created first so routes can be registered before Start().
	hs := health.NewHealthServer(
		kfg.Ork().Name,
		kfg.Health().Port,
		kfg.Ork().LogLevel,
		kat.ConversionRegistry(),
		health.ConversionOptions{
			ConvEnabled:      kfg.ConversionConfig().EnableConversion,
			ConvCert:         kfg.ConversionConfig().TLSCert,
			ConvKey:          kfg.ConversionConfig().TLSKey,
			ConversionWindow: kfg.ConversionConfig().ConversionWindow,
		},
	)

	// Kubeclient
	kube := kubeclient.NewKubeclient(kubeclient.Config{
		Kubeconfig: kfg.Cluster().KubekonfigPath,
		Masterurl:  kfg.Cluster().MasterURL,
		Scheme:     scheme,
	})

	// Start kubeclient as it may be needed by some downstream services
	// Example: Informerfactory now has to check for missing CRDs and needs rest config
	if err := kube.Start(ctx); err != nil {
		logger.Fatal().Err(err).Msg("failed to start kubeclient")
	}

	// Event recorder — wraps kube, also not live until kube.Start().
	ev := event.NewEvent(kube)

	// Default workqueue — shared fallback for CRDs with Queue.Default = true.
	defaultWq := queue.NewWorkqueue()

	// Per-CRD queue registry — each CRD gets an isolated queue.
	queueRegistry := queue.NewQueueRegistry()

	// ── 4a. Client provider ───────────────────────────────────────────────────
	// Registers a REST client constructor per CRD type.
	// Constructors are deferred — executed when the provider is first used.
	// Typed CRDs register a REST client constructor.
	// Dynamic CRDs skip this — they use NewDynamicListerWatcher directly
	// in the informer factory loop below.
	provider := kube.NewClientProvider()

	for _, crd := range kat.Enabled() {
		crd := crd // capture — closure must own its own crd value
		if crd.IsDynamic() {
			continue // dynamic path — registered per-informer below
		}

		object, list := crd.GetRuntimeObjects()

		logger.Debug().
			Str("gvk", crd.GVK().String()).
			Str("mode", string(crd.Mode)).
			Msg("registering CRD client provider")

		provider.Register(object, func(k *kubeclient.Kubeclient) (informer.GenericClient, error) {
			return k.NewClient(list, kubeclient.CRDInfo{
				Kind:         crd.APITypes.Kind,
				Group:        crd.APITypes.Group,
				Version:      crd.APITypes.Version,
				APIPath:      crd.APITypes.APIPath,
				GroupVersion: crd.GroupVersion,
				Plural:       crd.APITypes.Plural,
				Namespace:    crd.Namespace,
				Namespaced:   crd.IsNamespaced(),
			})
		})
	}

	// ── 4b. Shared informer factory ───────────────────────────────────────────
	// Routes API server events into the correct per-CRD queue via handleEvent.
	// Not started here — infFactory.Start() is called by orkestra.
	infFactory := informer.SharedInformerFactory(
		provider,
		kube.RestConfig(),
		queueRegistry,
		defaultWq,
		scheme,
		kfg.Cluster().DefaultNamespace,
		kfg.Cluster().DefaultResync,
	)

	// ── 4c. Kontroller registry + per-CRD wiring ──────────────────────────────
	// Registers informers and reconciler factories per CRD.
	// Factories are closures — NewGenericReconciler / Constructor called
	// only after orkestra starts, guaranteeing kube and ev are live.
	ktrlRegistry := kontroller.NewKontrollerRegistry()

	logger.Debug().Msg("wiring CRDs into kontroller registry...")

	finalizers := kfg.Finalizers()
	for _, crd := range kat.Enabled() {
		crd := crd
		gvk := crd.GVK().String()
		gvr := crd.GroupVersionResource
		crd.Workers = crd.SetWorkers(kfg.Cluster().DefaultWorkers)

		// GetRuntimeObjects populates DynamicModeObject
		// Already populated by addRuntimeObjects() during validation.
		object, _ := crd.GetRuntimeObjects()

		wq := queueRegistry.Register(gvk, crd.SetMaxQueueDepth(
			kfg.Katalog().DefaultMaxQueueDepth,
		))

		opts := informer.Options{
			Name:   crd.APITypes.Kind,
			Resync: crd.Resync,
		}

		if crd.DefaultQueue() {
			logger.Debug().Str("gvk", gvk).Msg("using default workqueue")
			opts.Wq = nil
		} else {
			opts.Wq = wq
		}

		// For each CRD, choose typed or dynamic informer based on mode.

		var inf cache.SharedIndexInformer

		if crd.IsDynamic() {
			// Dynamic informer — bypasses scheme entirely.
			// NewDynamicListerWatcher returns a cache.ListerWatcher that uses
			// the dynamic client directly. No scheme registration needed.
			lw := kube.NewDynamicListerWatcher(kubeclient.CRDInfo{
				Kind:         crd.APITypes.Kind,
				Group:        crd.APITypes.Group,
				Version:      crd.APITypes.Version,
				APIPath:      crd.APITypes.APIPath,
				GroupVersion: crd.GroupVersion,
				Plural:       crd.APITypes.Plural,
				Namespace:    crd.Namespace,
				Namespaced:   crd.IsNamespaced(),
			})

			inf = infFactory.ForListerWatcher(lw, object, ctx, opts)
		} else {
			// Typed informer — uses the REST client registered in 4a.
			inf = infFactory.For(object, ctx, opts)
		}

		finalizers = append(finalizers, crd.ReconcilerConfig.Finalizers...)
		crdInfo := reconciler.CRDInfo{
			Kind:             crd.APITypes.Kind,
			GVK:              gvk,
			GVR:              gvr,
			Operator:         kat.Meta().Name,
			Finalizers:       finalizers,
			ReconcilerConfig: crd.ReconcilerConfig,
		}
		infCopy := inf

		var factory func() domain.Reconciler

		if crd.DefaultReconcile() {
			// DynamicModeObject / TypedModeObject already set — GetRuntimeObjects handles mode.
			// We need a domain.Object factory for GenericReconciler.
			// object is already the correct concrete type for this CRD.
			objCopy := object // capture the concrete runtime.Object for this CRD

			var anyHooks domain.AnyReconcileHooks
			if crd.ReconcilerConfig.HookFactory != nil {
				anyHooks = crd.ReconcilerConfig.HookFactory()
			}

			logger.Debug().Str("gvk", gvk).Msg("wiring GenericReconciler factory")

			factory = func() domain.Reconciler {
				return reconciler.NewGenericReconciler(
					crdInfo,
					infCopy,
					ev,
					kube,
					anyHooks,
					func() domain.Object {
						// DeepCopyObject gives us a fresh zero-value instance
						// of the correct concrete type — no registry lookup needed.
						return objCopy.DeepCopyObject().(domain.Object)
					},
				)
			}

		} else {
			if crd.ReconcilerConfig.Constructor == nil {
				logger.Fatal().
					Str("gvk", gvk).
					Msg("reconciler.default is false but no Constructor provided")
			}

			logger.Debug().Str("gvk", gvk).Msg("wiring custom reconciler factory")

			factory = func() domain.Reconciler {
				return crd.ReconcilerConfig.Constructor(kube, infCopy, ev)
			}
		}

		ktrlRegistry.Register(gvk, crd, inf, factory)
		logger.Debug().Str("gvk", gvk).Msg("CRD registered")
	}
	// ── 5a. Per-CRD health map ────────────────────────────────────────────────
	// Built before routes and before NewDependencyKontroller so all three
	// share pointers to the same CRDHealth instances.
	//   startCRDWorkers  → RecordSuccess / RecordFailure per reconcile
	//   route handlers   → read health state on HTTP request
	crdHealthMap := make(map[string]*kontroller.CRDHealth)
	for _, crd := range kat.Enabled() {
		gvk := crd.GVK().String()
		crdHealthMap[gvk] = kontroller.NewCRDHealth(crd.Name)
	}

	// ── 5b. Health and Katalog API routes ─────────────────────────────────────
	// All routes must be registered before hs.Start() — the HTTP server
	// uses hs.mux which is the same mux Register() writes to.
	for _, crd := range kat.Enabled() {
		gvk := crd.GVK().String()
		crdHealth := crdHealthMap[gvk]
		crdName := strings.ToLower(crd.Name)

		// Get the informer for this CRD from the registry
		entry, _ := ktrlRegistry.Get(gvk)
		inf := entry.Informer // already stored on RegistryEntry

		if !crd.IsEnabledAllEndpoints() {
			continue
		}

		// GET /katalog/{crd}/health — 200 healthy, 503 degraded
		if crd.IsHealthEnabled() {
			hs.Register(
				"/katalog/"+crdName+"/health",
				kontroller.BuildCRDHealthHandler(crd, crdHealth),
			)
		}

		// GET /katalog/{crd} — CRD config + live reconcile stats
		if crd.IsInfoEnabled() {
			hs.Register(
				"/katalog/"+crdName,
				kontroller.BuildCRDInfoHandler(crd, kfg, inf, crdHealth, hs.GetConversionStats()),
			)
		}

		logger.Debug().
			Str("health", "/katalog/"+crdName+"/health").
			Str("info", "/katalog/"+crdName).
			Msg("registered CRD health routes")
	}

	// GET /katalog — aggregate view: all CRDs, dependency graph, health summary
	hs.Register("/katalog", kontroller.BuildKatalogHandler(kat, kfg, ktrlRegistry, crdHealthMap))

	// ── 6. Dependency kontroller ──────────────────────────────────────────────
	// Starts CRD workers in topological dependency order.
	// Calls ReconcilerFactory() per CRD after infFactory is live.
	// Passes crdHealthMap — health state updated per reconcile result.
	ktrl := kontroller.NewDependencyKontroller(
		kube,
		infFactory,
		ktrlRegistry,
		ev,
		hs,
		queueRegistry,
		defaultWq,
		crdHealthMap,
		kfg.Cluster().DefaultWorkers,
		katalog.NewDependencyGraph(kat),
	)

	// ── 7 Komponent list ─────────────────────────────────────────────────────
	// Orkestra starts these in order. Shutdown runs in reverse.
	komponents := []domain.Komponent{
		hs,            // 1. health server  — routes already registered above
		kube,          // 2. kubeclient     — REST config, dynamic client, clientset
		ev,            // 3. event recorder — depends on kube being started
		queueRegistry, // 4. per-CRD queues
		defaultWq,     // 5. default fallback queue
		infFactory,    // 6. informer factory — starts informers, closes ready channel
		ktrl,          // Kontroller is last — depends on everything above being started first.
	}

	// ── 8. Orkestra ────────────────────────────────────────────────────────────
	// Owns the full lifecycle of all komponents.
	// Start  : sequential, in registration order.
	// Shutdown: reverse order, on OS signal or fatal error.
	o := ork.NewOrkestra(kfg.Cluster().DefaultResync, kfg.Ork().LogLevel)
	o.Register(komponents)

	return &orkestraKfg{
		konfig:     kfg,
		katalog:    kat,
		komp:       &komponents,
		event:      ev,
		kube:       kube,
		kontroller: ktrl,
		orkestra:   o,
	}
}
