// pkg/runtime/zz_generated_runtime_registry.go
// Code generated by "ork generate registry" on 2026-05-01T04:18:14Z. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
//
// This file registers compiled Go types and external functions.
// Dynamic template CRDs do not appear here — they are handled at runtime
// by GenericReconciler without any code generation.
package runtime

import (
	"github.com/orkspace/orkestra/domain"
	"github.com/orkspace/orkestra/pkg/logger"
	orktypes "github.com/orkspace/orkestra/pkg/types"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	demov1alpha1 "github.com/orkspace/orkestra-hooks-demo/api/v1alpha1"
	dbhooks "github.com/orkspace/orkestra-hooks-demo/hooks"
)

// init runs before main(). It calls RegisterRuntimeObjects to populate the
// GVK-keyed registries and appends AddToScheme functions to SchemeAdderFns so
// that NewSchemeRegistry can find them through the internal pkg/runtime stub.
//
// A blank import of this package from main.go is the only wiring needed:
//
//	import _ "myapp/pkg/runtime"
//
// "ork generate registry -k <katalog.yaml>" populates this
//
// No explicit call to RegisterRuntimeObjects or RegisterTypedScheme is required.
func init() {
	logger.Debug().Msg("runtime.init() started")
	RegisterRuntimeObjects()
	orktypes.SchemeAdderFns = append(orktypes.SchemeAdderFns, demov1alpha1.AddToScheme)
	logger.Debug().Int("length", len(orktypes.SchemeAdderFns)).Msg("runtime.init() finished")
}

// RegisterRuntimeObjects populates ObjectRegistry, ListRegistry, HookRegistry,
// and ReconcilerRegistry. Called by init() — do not call directly.
//
// Object/List entries — factory functions for typed CRDs.
//
//	Used by the informer to create zero-value instances for cache storage
//	and type assertion during reconciliation.
//
// Hook entries — factory functions for Go hook implementations.
//
//	Called by addHooks() during Katalog validation to wire HookFactory
//	onto the CRD entry. GenericReconciler calls HookFactory() once at
//	startCRDWorkers time to obtain the typed hooks.
//
// Reconciler entries — constructor functions for custom reconcilers.
//
//	Called by addReconcilers() during Katalog validation to wire Constructor
//	onto the CRD entry. DependencyKordinator calls Constructor() once at
//	startCRDWorkers time to build the reconciler.
func RegisterRuntimeObjects() {
	logger.Debug().Msg("RegisterRuntimeObjects called")

	// Database — typed CRD object and list factories
	orktypes.ObjectRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "Database"}] =
		func() runtime.Object { return &demov1alpha1.Database{} }
	orktypes.ListRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "Database"}] =
		func() runtime.Object { return &demov1alpha1.DatabaseList{} }

	// Database — Go hook factory
	// Calls dbhooks.DatabaseHooks() to obtain typed ReconcileHooks.
	orktypes.HookRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "Database"}] =
		func() domain.AnyReconcileHooks {
			return dbhooks.DatabaseHooks()
		}

	logger.Debug().
		Int("objectRegistrySize", len(orktypes.ObjectRegistry)).
		Int("listRegistrySize", len(orktypes.ListRegistry)).
		Int("hookRegistrySize", len(orktypes.HookRegistry)).
		Msg("Runtime objects registered")
}
