// pkg/runtime/zz_generated_runtime_registry.go
// Code generated by "ork generate runtime" on 2026-04-03T01:09:54Z. DO NOT EDIT.
// Re-generate by running: ork generate runtime --katalog <path-or-url>
//
// This file registers compiled Go types and external functions.
// Dynamic template CRDs do not appear here — they are handled at runtime
// by GenericReconciler without any code generation.
package runtime

import (
	"fmt"

	"github.com/ialexeze/orkestra/domain"
	orktypes "github.com/ialexeze/orkestra/pkg/types"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	dbhook "orkestra-hooks-demo/09-hooks/hooks"
	db "orkestra-hooks-demo/09-hooks/v1alpha1"
)

// RegisterRuntimeObjects populates ObjectRegistry, ListRegistry, HookRegistry,
// and ReconcilerRegistry. Called once at startup before Katalog validation.
//
// Object/List entries — factory functions for typed CRDs.
//
//	Used by the informer to create zero-value instances for cache storage
//	and type assertion during reconciliation.
//
// Hook entries — factory functions for Go hook implementations.
//
//	Called by addHooks() during Katalog validation to wire HookFactory
//	onto the CRD entry. GenericReconciler calls HookFactory() once at
//	startCRDWorkers time to obtain the typed hooks.
//
// Reconciler entries — constructor functions for custom reconcilers.
//
//	Called by addReconcilers() during Katalog validation to wire Constructor
//	onto the CRD entry. DependencyKordinator calls Constructor() once at
//	startCRDWorkers time to build the reconciler.
func RegisterRuntimeObjects() {

	// Database — typed CRD object and list factories
	orktypes.ObjectRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "Database"}] =
		func() runtime.Object { return &db.Database{} }
	orktypes.ListRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "Database"}] =
		func() runtime.Object { return &db.DatabaseList{} }

	// Database — Go hook factory
	// Calls dbhook.DatabaseHooks() to obtain typed ReconcileHooks.
	orktypes.HookRegistry[schema.GroupVersionKind{Group: "demo.orkestra.io", Version: "v1alpha1", Kind: "Database"}] =
		func() domain.AnyReconcileHooks {
			return dbhook.DatabaseHooks()
		}

}

// RegisterTypedScheme registers the AddToScheme function for each typed CRD.
// Called by NewSchemeRegistry during startup so the REST client can decode
// API server responses into compiled Go structs.
//
// Dynamic CRDs do not appear here — *unstructured.Unstructured is registered
// separately in registerDynamicScheme using AddKnownTypeWithName.
func RegisterTypedScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
	if err := db.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register Database scheme: %w", err)
	}
	return scheme, nil
}
