package doktor

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	BundleFile      = "bundle.yaml"
	AppSecretFile   = "app-secrets.yaml"
	AppConfigFile   = "app-config.yaml"
	ApplicationFile = "app.yaml"

	Orkestra          = "orkestra"
	OrkestraRuntime   = "orkestra-runtime"
	OrkestraNamespace = "orkestra-system"
	OrkestraChartRepo = "https://orkspace.github.io/orkestra"
	OrkestraChartName = "orkestra/orkestra"
)

// GenerateBundle writes the app Secret and ConfigMap YAML files into outputDir.
// The caller is responsible for creating outputDir before calling.
func GenerateBundle(name, namespace string, secrets, config []EnvVar, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("creating bundle dir: %w", err)
	}

	if len(secrets) > 0 {
		secretYAML := buildSecret(name, namespace, secrets)
		path := filepath.Join(outputDir, AppSecretFile)
		if err := os.WriteFile(path, []byte(secretYAML), 0o600); err != nil {
			return fmt.Errorf("writing app-secrets.yaml: %w", err)
		}
	}

	if len(config) > 0 {
		configYAML := buildConfigMap(name, namespace, config)
		path := filepath.Join(outputDir, AppConfigFile)
		if err := os.WriteFile(path, []byte(configYAML), 0o644); err != nil {
			return fmt.Errorf("writing app-config.yaml: %w", err)
		}
	}

	return nil
}

func buildSecret(name, namespace string, vars []EnvVar) string {
	var b strings.Builder
	b.WriteString("# .orkestra/bundle/app-secrets.yaml\n")
	b.WriteString("# Generated by ork deploy — DO NOT COMMIT THIS FILE\n")
	b.WriteString("# Add .orkestra/bundle/ to .gitignore\n\n")
	b.WriteString("apiVersion: v1\n")
	b.WriteString("kind: Secret\n")
	b.WriteString("metadata:\n")
	b.WriteString(fmt.Sprintf("  name: %s-secrets\n", name))
	b.WriteString(fmt.Sprintf("  namespace: %s\n", namespace))
	b.WriteString("type: Opaque\n")
	b.WriteString("data:\n")
	for _, v := range vars {
		encoded := base64.StdEncoding.EncodeToString([]byte(v.Value))
		b.WriteString(fmt.Sprintf("  %s: %s\n", v.Key, encoded))
	}
	return b.String()
}

func buildConfigMap(name, namespace string, vars []EnvVar) string {
	var b strings.Builder
	b.WriteString("# .orkestra/bundle/app-config.yaml\n")
	b.WriteString("# Generated by ork deploy — DO NOT COMMIT THIS FILE\n\n")
	b.WriteString("apiVersion: v1\n")
	b.WriteString("kind: ConfigMap\n")
	b.WriteString("metadata:\n")
	b.WriteString(fmt.Sprintf("  name: %s-config\n", name))
	b.WriteString(fmt.Sprintf("  namespace: %s\n", namespace))
	b.WriteString("data:\n")
	for _, v := range vars {
		b.WriteString(fmt.Sprintf("  %s: %q\n", v.Key, v.Value))
	}
	return b.String()
}
