apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.ecosystem.demo.orkestra.io
spec:
  group: ecosystem.demo.orkestra.io
  names:
    kind: App
    plural: apps
    singular: app
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [repo, path, branch, targetNamespace]
              properties:
                repo:
                  type: string
                  description: Git repository URL (without https://)
                path:
                  type: string
                  description: Path to the app manifests within the repo
                branch:
                  type: string
                  description: Git branch to track
                targetNamespace:
                  type: string
                  description: Namespace to deploy into
                autoSync:
                  type: boolean
                  default: true
                labels:
                  type: object
                  description: Labels to be applied to application resources
                  additionalProperties:
                    type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
