apiVersion: provisioner.orkestra.io/v1
kind: NamespaceClaim
metadata:
  name: team-beta-claim
spec:
  targetNamespace: team-beta
  team: beta
  owner: beta-operator
  ownerNamespace: default
  tier: medium
