//go:build !runtime

package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/orkspace/orkestra/pkg/generate"
	"github.com/orkspace/orkestra/pkg/logger"
	"github.com/spf13/cobra"
)

var generateRegistryCmd = &cobra.Command{
	Use:   "registry",
	Short: "Generate 'pkg/runtime/zz_generated_runtime_registry.go' from a Katalog",
	Long:  `...`,
	RunE: func(cmd *cobra.Command, args []string) error {
		out, err := generateKatalog(cmd)
		if err != nil {
			return err
		}

		dryRun, _ := cmd.Flags().GetBool("dry-run")

		// Validate Go project
		root, moduleName, err := validateProject()
		if err != nil {
			return err
		}

		logger.Info().Msg("generating runtime registry...")
		if err := generate.Runtime(out.m, dryRun); err != nil {
			return fmt.Errorf("generate runtime registry: %w", err)
		}

		logger.Info().Msg("runtime registry generated successfully")
		logger.Info().Str("registry", filepath.Join(generate.RuntimePackage, generate.RegistryFile)).Msg("")

		// --- Ensure main.go exists with the blank import ---
		// Should run after the registry is successful
		if err := ensureMainGo(root, moduleName, dryRun); err != nil {
			logger.Warn().Err(err).Msg("failed to ensure main.go – you may need to add import manually")
		}

		return nil
	},
}

// validateProject verifies the current working directory is inside a Go module.
// It returns the absolute project root (directory containing go.mod), the module
// path declared in that go.mod, and a non-nil error if either step fails.
func validateProject() (string, string, error) {
	// Locate project root (where go.mod exists)
	root, err := findProjectRoot()
	if err != nil {
		return "", "", fmt.Errorf("finding project root: %w", err)
	}

	// Read module name from go.mod
	moduleName, err := readModuleName(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", "", fmt.Errorf("reading module name: %w", err)
	}

	// Log the discovered project root and module name
	logger.Debug().
		Str("project_root", root).
		Str("module", moduleName).
		Msg("validated Go project")

	return root, moduleName, nil
}

// ensureMainGo creates or overwrites cmd/orkestra/main.go with the required blank import.
// It always writes the standard template – do not preserve user modifications.
func ensureMainGo(root, moduleName string, dryRun bool) error {
	targetDir := filepath.Join(root, "cmd", "orkestra")
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		return fmt.Errorf("creating cmd/orkestra: %w", err)
	}
	mainPath := filepath.Join(targetDir, "main.go")

	timestamp := time.Now().UTC().Format(time.RFC3339)
	importLine := fmt.Sprintf(`_ "%s/pkg/runtime"`, moduleName)

	content := fmt.Sprintf(`// Code generated by "ork generate registry" on %s. DO NOT EDIT.
// Re-generate by running: ork generate registry --katalog <path-or-url>
package main

import (
    "context"

    "github.com/orkspace/orkestra/cmd/cli"
    "github.com/orkspace/orkestra/pkg/konfig"
    "github.com/orkspace/orkestra/pkg/logger"
    "github.com/orkspace/orkestra/pkg/utils"

    %s
)

func main() {
    kfg, err := konfig.Init()
    if err != nil {
        logger.Fatal().AnErr("failed to load configurations", err)
        utils.Exit(err)
    }
    ctx, cancel := context.WithCancel(context.Background())
    defer cancel()
    cli.Execute(kfg, ctx)
}`, timestamp, importLine)

	if dryRun {
		fmt.Println(content)
		return nil
	}

	return os.WriteFile(mainPath, []byte(content), 0644)
}

// findProjectRoot returns the current working directory if it contains go.mod.
// It fails fast if go.mod is not present in the current directory.
func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getting working directory: %w", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
		return dir, nil
	}
	return "", fmt.Errorf("go.mod not found in current directory: %s", dir)
}

// readModuleName extracts the module path from go.mod.
func readModuleName(modPath string) (string, error) {
	f, err := os.Open(modPath)
	if err != nil {
		return "", err
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "module ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				return parts[1], nil
			}
		}
	}
	return "", fmt.Errorf("module declaration not found in %s", modPath)
}
