# 06 — full stack (apply 03a first so database is available)
apiVersion: advanced.orkestra.io/v1alpha1
kind: FullStackApp
metadata:
  name: my-app        # To make it easy to reference my-app-db in 'cross'
  namespace: default
spec:
  image: nginx:1.25
  regions:
    - us-east-1
    - eu-west-1
    - ap-southeast-1
  replicasPerRegion: 1
  serviceUrl: "https://waas.ondgo.dev"   # replace with your service
  environment: "production"
  notify: "true"