[ req ]
default_bits       = 2048
prompt             = no
default_md         = sha256
req_extensions     = req_ext
distinguished_name = dn

[ dn ]
CN = orkestra.orkestra.svc

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = orkestra
DNS.2 = orkestra.orkestra
DNS.3 = orkestra.orkestra.svc
DNS.4 = orkestra.orkestra.svc.cluster.local
