apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.demo.orkestra.io
spec:
  group: demo.orkestra.io
  scope: Namespaced
  names:
    plural: webapps
    singular: webapp
    kind: WebApp
    shortNames: [wa]
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: SupplyChain
          type: string
          jsonPath: .status.supplyChainPhase
        - name: Vault
          type: string
          jsonPath: .status.vaultPhase
        - name: Policy
          type: string
          jsonPath: .status.policyPhase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [image, serviceUrl]
              properties:
                image:
                  type: string
                serviceUrl:
                  type: string
                  description: Base URL used by all three motifs (dev server handles all endpoints).
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
