name: Publish Winget Manifests

on:
  workflow_call:

jobs:
  winget:
    name: Publish Winget Manifests
    runs-on: windows-latest
    steps:
      - name: Publish Orkestra CLI to WinGet
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Orkspace.Orkestra
          installers-regex: 'ork_windows_amd64\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
          release-tag: ${{ github.ref_name }}

      - name: Publish Orkestra Control Center to WinGet
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Orkspace.OrkestraControlCenter
          installers-regex: 'orkcc_windows_amd64\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
          release-tag: ${{ github.ref_name }}