---
# platform-team CRD
apiVersion: multi-tenancy.orkestra.io/v1alpha1
kind: Database
metadata:
  name: main-db
  namespace: default
spec:
  engine: postgres
---
# product-team CRD
apiVersion: multi-tenancy.orkestra.io/v1alpha1
kind: Website
metadata:
  name: storefront
  namespace: default
spec:
  image: nginx:alpine
  replicas: 1
